<?php declare( strict_types=1 );

namespace FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Reports\Contexts;

use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Email\EmailBase;
use FernleafSystems\Wordpress\Plugin\Shield\Modules\Plugin\Lib\Reporting\ReportVO;
use FernleafSystems\Wordpress\Services\Services;

abstract class EmailReportBase extends EmailBase {

	protected function report() :ReportVO {
		return $this->action_data[ 'report' ];
	}

	protected function detailLevel() :string {
		return (string)( $this->action_data[ 'detail_level' ] ?? 'detailed' );
	}

	protected function buildReportMeta( ?ReportVO $report = null ) :array {
		$report = $report ?? $this->report();
		$WP = Services::WpGeneral();
		$reportCon = self::con()->comps->reports;
		$isHourly = ( $report->interval ?? '' ) === 'hourly';

		return [
			'href'       => $reportCon->getReportURL( $report->record->unique_id ),
			'date_start' => $WP->getTimeStringForDisplay( $report->start_at, $isHourly ),
			'date_end'   => $WP->getTimeStringForDisplay( $report->end_at, $isHourly ),
		];
	}

	protected function commonStrings() :array {
		return [
			'generated_by_plugin'=> \sprintf(
				__( 'Generated by %s', 'wp-simple-firewall' ),
				self::con()->labels->Name
			),
			'view_full_report' => __( 'View Full Report', 'wp-simple-firewall' ),
			'security_report'  => __( 'Security Report', 'wp-simple-firewall' ),
			'security_alert'   => __( 'Security Alert', 'wp-simple-firewall' ),
			'new_badge'        => __( 'NEW', 'wp-simple-firewall' ),
			'and_x_more'       => __( '... and %s more', 'wp-simple-firewall' ),
		];
	}

	protected function getRequiredDataKeys() :array {
		return [
			'home_url',
			'report',
		];
	}
}
