const js = require( '@eslint/js' );

module.exports = [
	{
		files: [
			'assets/js/util/ObjectOps.js',
			'assets/js/components/services/AjaxBatchService.js',
			'assets/js/components/tables/ActivityLogMetaPopover.js',
			'assets/js/components/tables/InvestigationTable.js',
			'assets/js/components/tables/ShieldTableActivityLog.js',
			'assets/js/components/tables/ShieldTableBase.js',
			'assets/js/components/tables/ShieldTableIpRules.js',
			'assets/js/components/tables/ShieldTableSecurityRules.js',
			'assets/js/components/tables/ShieldTableSessions.js',
			'assets/js/components/mode/ConfigureExpandLoader.js',
			'assets/js/components/mode/StepTabsController.js',
			'assets/js/components/mode/ActionsQueueLandingController.js',
			'assets/js/plugin-login_2fa.js',
			'assets/js/components/login2fa/Login2faHandler.js',
			'assets/js/components/login2fa/Login2faEmail.js',
			'assets/js/components/login2fa/Login2faGoogleAuth.js',
			'assets/js/components/login2fa/Login2faOtpSegments.js',
			'assets/js/components/login2fa/ShieldLoginIntentUi.js',
		],
		languageOptions: {
			ecmaVersion: 'latest',
			sourceType: 'module',
			globals: {
				window: 'readonly',
				global: 'readonly',
				document: 'readonly',
				Element: 'readonly',
				HTMLElement: 'readonly',
				Node: 'readonly',
				HTMLTableElement: 'readonly',
				HTMLButtonElement: 'readonly',
				HTMLInputElement: 'readonly',
				Event: 'readonly',
				KeyboardEvent: 'readonly',
				ClipboardEvent: 'readonly',
				HTMLFormElement: 'readonly',
				CustomEvent: 'readonly',
				URL: 'readonly',
				WeakSet: 'readonly',
				setTimeout: 'readonly',
				clearTimeout: 'readonly',
				setInterval: 'readonly',
				clearInterval: 'readonly',
				alert: 'readonly',
				confirm: 'readonly',
				console: 'readonly',
				shieldAppMain: 'readonly',
				shieldEventsHandler_Main: 'readonly',
				shieldEventsHandler_Login2fa: 'readonly',
				shieldStrings: 'readonly',
				shieldServices: 'readonly',
				ajaxurl: 'readonly',
			},
		},
		rules: {
			...js.configs.recommended.rules,
			'no-unused-vars': [ 'error', { args: 'none' } ],
		},
	},
];
