<?php declare( strict_types=1 );

namespace FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\FullPage\Report;

use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Traits\AuthNotRequired;
use FernleafSystems\Wordpress\Plugin\Shield\Modules\Plugin\Lib\Reporting\{
	ReportVO,
	ResolveReportViewContracts
};
use FernleafSystems\Wordpress\Services\Services;

class SecurityReportAlert extends \FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\FullPage\BaseFullPageRender {

	use AuthNotRequired;

	public const SLUG = 'render_security_report_alert';
	public const TEMPLATE = '/pages/report/security_alert.twig';

	protected function getRenderData() :array {
		$con = self::con();
		$WP = Services::WpGeneral();
		$report = ( new ReportVO() )->applyFromArray( $this->action_data[ 'report' ] );
		$digest = ( new ResolveReportViewContracts() )->alertDigest( $report );

		return [
			'strings' => [
				'report_header_title'    => sprintf( __( '%s Website Security Alert', 'wp-simple-firewall' ), $con->labels->Name ),
				'intro'                  => __( 'These are the current critical issues on your site that require action, split between new issues and older unresolved issues.', 'wp-simple-firewall' ),
				'generated_by_plugin'    => \sprintf( __( 'Report generated by %s', 'wp-simple-firewall' ), $con->labels->Name ),
				'new_issues'             => __( 'New Issues', 'wp-simple-firewall' ),
				'outstanding_issues'     => __( 'Still Outstanding', 'wp-simple-firewall' ),
				'current_issues'         => __( 'Current Critical Issues', 'wp-simple-firewall' ),
				'review_scan_results'    => __( 'Review Scan Results', 'wp-simple-firewall' ),
				'new_badge'              => __( 'NEW', 'wp-simple-firewall' ),
				'and_x_more'             => __( '... and %s more', 'wp-simple-firewall' ),
			],
			'vars'    => [
				'interval'      => $report->interval ?? '',
				'dates'         => [
					'generation_date'        => $WP->getTimeStringForDisplay( null, false ),
					'generation_time'        => $WP->getTimeStringForDisplay(),
					'report_date_start'      => $WP->getTimeStringForDisplay( $report->start_at, false ),
					'report_date_end'        => $WP->getTimeStringForDisplay( $report->end_at, false ),
					'report_date_full_start' => $WP->getTimeStringForDisplay( $report->start_at ),
					'report_date_full_end'   => $WP->getTimeStringForDisplay( $report->end_at ),
				],
				'site_url_host' => \wp_parse_url( $WP->getHomeUrl(), \PHP_URL_HOST ),
				'digest'        => $digest,
			],
		];
	}
}
