<?php declare( strict_types=1 );

namespace FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\DBs;

use FernleafSystems\Wordpress\Plugin\Shield\Controller\Database\DbCon;
use FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\ShieldIntegrationTestCase;
use FernleafSystems\Wordpress\Services\Services;

/**
 * Diagnostic tests for the SQL generated by Shield's database schemas.
 */
class DbCreateTableDiagnosticTest extends ShieldIntegrationTestCase {

	/**
	 * Build every handler's CREATE TABLE SQL, redirect it to a unique disposable
	 * probe table, and report whether MySQL accepts that schema SQL.
	 *
	 * @group diagnostics
	 * @group database-transaction-exception
	 */
	public function test_diagnose_table_creation_failures() :void {
		if ( !$this->isVerbose() ) {
			$this->markTestSkipped( 'DB diagnostics disabled. Set SHIELD_TEST_VERBOSE=1 to run this diagnostic test.' );
		}

		$probeTable = $this->newProbeTableName();
		$diagnostics = $this->runSchemaDiagnostics( $probeTable );
		$failures = $this->diagnosticFailures( $diagnostics );

		\fwrite( STDERR, $this->formatDiagnosticOutput( $probeTable, $diagnostics, $failures ) );
		$this->assertDiagnosticsSuccessful( $diagnostics, $failures );
		$this->assertProbeTableAbsentRaw( $probeTable );
	}

	/**
	 * @group database-transaction-exception
	 */
	public function test_invalid_probe_sql_fails_diagnostic() :void {
		$probeTable = $this->newProbeTableName();
		$createFailed = false;
		$filter = static function ( string $query ) use ( $probeTable, &$createFailed ) :string {
			if ( !$createFailed
				 && \stripos( $query, 'CREATE TABLE IF NOT EXISTS' ) !== false
				 && \strpos( $query, "`{$probeTable}`" ) !== false ) {
				$createFailed = true;
				return 'THIS IS INTENTIONALLY INVALID PROBE CREATE SQL';
			}
			return $query;
		};

		$diagnostics = $this->runSchemaDiagnosticsWithQueryFilter( $probeTable, $filter );
		$firstKey = \array_key_first( DbCon::MAP );

		$this->assertTrue( $createFailed );
		$this->assertDiagnosticsHaveExactKeys( $diagnostics );
		$this->assertSame( 'schema_sql_invalid', $diagnostics[ $firstKey ][ 'status' ] );
		$this->assertNotEmpty( $diagnostics[ $firstKey ][ 'mysql_error' ] );
		$this->assertArrayHasKey( $firstKey, $this->diagnosticFailures( $diagnostics ) );
		$this->assertProbeTableAbsentRaw( $probeTable );
	}

	/**
	 * @group database-transaction-exception
	 */
	public function test_cleanup_failure_stops_following_handlers() :void {
		$probeTable = $this->newProbeTableName();
		$dropCount = 0;
		$cleanupFailed = false;
		$filter = static function ( string $query ) use ( $probeTable, &$dropCount, &$cleanupFailed ) :string {
			if ( \stripos( $query, 'DROP TABLE IF EXISTS' ) !== false
				 && \strpos( $query, "`{$probeTable}`" ) !== false ) {
				++$dropCount;
				if ( $dropCount === 2 ) {
					$cleanupFailed = true;
					return 'THIS IS INTENTIONALLY INVALID PROBE CLEANUP SQL';
				}
			}
			return $query;
		};

		$diagnostics = $this->runSchemaDiagnosticsWithQueryFilter( $probeTable, $filter );
		$keys = \array_keys( DbCon::MAP );

		$this->assertTrue( $cleanupFailed );
		$this->assertDiagnosticsHaveExactKeys( $diagnostics );
		$this->assertSame( 'probe_cleanup_failed', $diagnostics[ $keys[ 0 ] ][ 'status' ] );
		$this->assertNotEmpty( $diagnostics[ $keys[ 0 ] ][ 'cleanup_error' ] );
		foreach ( \array_slice( $keys, 1 ) as $key ) {
			$this->assertSame( 'not_run_after_cleanup_failure', $diagnostics[ $key ][ 'status' ] );
		}
		$this->assertProbeTableAbsentRaw( $probeTable );
	}

	/**
	 * @group database-transaction-exception
	 */
	public function test_pre_cleanup_failure_prevents_create_and_stops_following_handlers() :void {
		$probeTable = $this->newProbeTableName();
		$cleanupFailed = false;
		$createAttempted = false;
		$filter = static function ( string $query ) use ( $probeTable, &$cleanupFailed, &$createAttempted ) :string {
			if ( \stripos( $query, 'CREATE TABLE IF NOT EXISTS' ) !== false
				 && \strpos( $query, "`{$probeTable}`" ) !== false ) {
				$createAttempted = true;
			}
			if ( !$cleanupFailed
				 && \stripos( $query, 'DROP TABLE IF EXISTS' ) !== false
				 && \strpos( $query, "`{$probeTable}`" ) !== false ) {
				$cleanupFailed = true;
				return 'THIS IS INTENTIONALLY INVALID PROBE PRE-CLEANUP SQL';
			}
			return $query;
		};

		$diagnostics = $this->runSchemaDiagnosticsWithQueryFilter( $probeTable, $filter );
		$keys = \array_keys( DbCon::MAP );

		$this->assertTrue( $cleanupFailed );
		$this->assertFalse( $createAttempted );
		$this->assertDiagnosticsHaveExactKeys( $diagnostics );
		$this->assertSame( 'probe_cleanup_failed', $diagnostics[ $keys[ 0 ] ][ 'status' ] );
		$this->assertNotEmpty( $diagnostics[ $keys[ 0 ] ][ 'cleanup_error' ] );
		foreach ( \array_slice( $keys, 1 ) as $key ) {
			$this->assertSame( 'not_run_after_cleanup_failure', $diagnostics[ $key ][ 'status' ] );
		}
		$this->assertProbeTableAbsentRaw( $probeTable );
	}

	/**
	 * @group database-transaction-exception
	 */
	public function test_schema_and_cleanup_failures_are_both_reported() :void {
		$probeTable = $this->newProbeTableName();
		$createFailed = false;
		$dropCount = 0;
		$cleanupFailed = false;
		$filter = static function ( string $query ) use (
			$probeTable,
			&$createFailed,
			&$dropCount,
			&$cleanupFailed
		) :string {
			if ( !$createFailed
				 && \stripos( $query, 'CREATE TABLE IF NOT EXISTS' ) !== false
				 && \strpos( $query, "`{$probeTable}`" ) !== false ) {
				$createFailed = true;
				return 'THIS IS INTENTIONALLY INVALID PROBE CREATE SQL';
			}
			if ( \stripos( $query, 'DROP TABLE IF EXISTS' ) !== false
				 && \strpos( $query, "`{$probeTable}`" ) !== false ) {
				++$dropCount;
				if ( $dropCount === 2 ) {
					$cleanupFailed = true;
					return 'THIS IS INTENTIONALLY INVALID PROBE CLEANUP SQL';
				}
			}
			return $query;
		};

		$diagnostics = $this->runSchemaDiagnosticsWithQueryFilter( $probeTable, $filter );
		$firstKey = \array_key_first( DbCon::MAP );

		$this->assertTrue( $createFailed );
		$this->assertTrue( $cleanupFailed );
		$this->assertDiagnosticsHaveExactKeys( $diagnostics );
		$this->assertSame( 'schema_sql_invalid_and_cleanup_failed', $diagnostics[ $firstKey ][ 'status' ] );
		$this->assertNotEmpty( $diagnostics[ $firstKey ][ 'mysql_error' ] );
		$this->assertNotEmpty( $diagnostics[ $firstKey ][ 'cleanup_error' ] );
		foreach ( \array_slice( \array_keys( DbCon::MAP ), 1 ) as $key ) {
			$this->assertSame( 'not_run_after_cleanup_failure', $diagnostics[ $key ][ 'status' ] );
		}
		$this->assertProbeTableAbsentRaw( $probeTable );
	}

	private function newProbeTableName() :string {
		global $wpdb;

		return $wpdb->prefix.'shield_schema_probe_'.\substr(
			\sha1( __CLASS__.\microtime( true ).\getmypid().\random_int( 0, \PHP_INT_MAX ) ),
			0,
			12
		);
	}

	/**
	 * @return array<string,array<string,string>>
	 */
	private function runSchemaDiagnostics( string $probeTable ) :array {
		$con = $this->requireController();
		$diagnostics = [];

		$this->runWithPersistentDatabaseMutation(
			function () use ( $con, $probeTable, &$diagnostics ) :void {
				$dbDefs = $con->cfg->configuration->databases[ 'tables' ];
				$cleanupUnsafe = false;

				foreach ( DbCon::MAP as $dbKey => $dbSpec ) {
					if ( $cleanupUnsafe ) {
						$diagnostics[ $dbKey ] = [
							'status' => 'not_run_after_cleanup_failure',
						];
						continue;
					}

					$diagnostic = null;
					try {
						try {
							$this->dropProbeTable( $probeTable, 'Pre-clean' );
						}
						catch ( \Throwable $e ) {
							$cleanupUnsafe = true;
							$diagnostic = [
								'status'        => 'probe_cleanup_failed',
								'probe_table'   => $probeTable,
								'cleanup_error' => $e->getMessage(),
							];
						}

						if ( !$cleanupUnsafe ) {
							try {
								$dbDef = $dbDefs[ $dbKey ];
								$dbDef[ 'table_prefix' ] = $con->getPluginPrefix( '_' );
								$handlerClass = $dbSpec[ 'handler_class' ];
								$handler = new $handlerClass( $dbDef );
								$schema = $handler->getTableSchema();
								$createSQL = $schema->buildCreate();
								$probeSQL = \preg_replace(
									'/CREATE TABLE IF NOT EXISTS\s+`'.\preg_quote( $schema->table, '/' ).'`/i',
									"CREATE TABLE IF NOT EXISTS `{$probeTable}`",
									$createSQL,
									1,
									$replacementCount
								);
								if ( $replacementCount !== 1 || !\is_string( $probeSQL ) ) {
									throw new \RuntimeException( 'Could not redirect CREATE TABLE SQL to the disposable probe.' );
								}

								[ $createResult, $mysqlError ] = $this->executeProbeCreate( $probeSQL );
								$diagnostic = [
									'status'       => $createResult === false || $mysqlError !== ''
										? 'schema_sql_invalid'
										: 'schema_sql_valid',
									'source_table' => $schema->table,
									'probe_table'  => $probeTable,
								];
								if ( $createResult === false || $mysqlError !== '' ) {
									$diagnostic[ 'mysql_error' ] = $mysqlError !== ''
										? $mysqlError
										: 'CREATE returned false without a database error.';
									$diagnostic[ 'sql' ] = $probeSQL;
								}
							}
							catch ( \Throwable $e ) {
								$diagnostic = [
									'status'      => 'diagnostic_exception',
									'probe_table' => $probeTable,
									'error'       => $e->getMessage(),
								];
							}
						}
					}
					finally {
						try {
							$this->dropProbeTable( $probeTable, 'Per-handler cleanup' );
						}
						catch ( \Throwable $e ) {
							$cleanupUnsafe = true;
							if ( $diagnostic === null ) {
								$diagnostic = [
									'status'        => 'probe_cleanup_failed',
									'probe_table'   => $probeTable,
									'cleanup_error' => $e->getMessage(),
								];
							}
							elseif ( $diagnostic[ 'status' ] === 'schema_sql_valid' ) {
								$diagnostic[ 'status' ] = 'probe_cleanup_failed';
								$diagnostic[ 'cleanup_error' ] = $e->getMessage();
							}
							else {
								$diagnostic[ 'status' ] .= '_and_cleanup_failed';
								$diagnostic[ 'cleanup_error' ] = isset( $diagnostic[ 'cleanup_error' ] )
									? $diagnostic[ 'cleanup_error' ].' '.$e->getMessage()
									: $e->getMessage();
							}
						}
					}

					$diagnostics[ $dbKey ] = $diagnostic ?? [
						'status'      => 'diagnostic_exception',
						'probe_table' => $probeTable,
						'error'       => 'The diagnostic produced no result.',
					];
				}
			},
			function () use ( $probeTable ) :void {
				$this->dropProbeTable( $probeTable, 'Outer restoration' );
				Services::WpDb()->clearResultShowTables();
				$this->requireProbeTableAbsentRaw( $probeTable );
			}
		);

		return $diagnostics;
	}

	/**
	 * @return array{0:int|bool,1:string}
	 */
	private function executeProbeCreate( string $sql ) :array {
		global $wpdb;

		$previousSuppressErrors = $wpdb->suppress_errors( true );
		try {
			$wpdb->last_error = '';
			$result = $wpdb->query( $sql );
			$mysqlError = (string)$wpdb->last_error;
		}
		finally {
			$wpdb->suppress_errors( $previousSuppressErrors );
		}

		return [ $result, $mysqlError ];
	}

	private function dropProbeTable( string $probeTable, string $context ) :void {
		global $wpdb;

		$wpdb->last_error = '';
		$result = $wpdb->query( "DROP TABLE IF EXISTS `{$probeTable}`" );
		$mysqlError = (string)$wpdb->last_error;
		if ( $result === false || $mysqlError !== '' ) {
			throw new \RuntimeException( \sprintf(
				'%s failed: %s',
				$context,
				$mysqlError !== '' ? $mysqlError : 'DROP returned false without a database error.'
			) );
		}
	}

	/**
	 * @return array<string,array<string,string>>
	 */
	private function runSchemaDiagnosticsWithQueryFilter( string $probeTable, callable $filter ) :array {
		global $wpdb;

		$previousSuppressErrors = $wpdb->suppress_errors( true );
		$diagnostics = null;
		$diagnosticFailure = null;
		\add_filter( 'query', $filter, \PHP_INT_MAX, 1 );
		try {
			$diagnostics = $this->runSchemaDiagnostics( $probeTable );
		}
		catch ( \Throwable $e ) {
			$diagnosticFailure = $e;
		}
		finally {
			\remove_filter( 'query', $filter, \PHP_INT_MAX );
			$wpdb->suppress_errors( $previousSuppressErrors );
		}

		try {
			if ( $diagnosticFailure !== null ) {
				throw $diagnosticFailure;
			}
			$this->assertFalse( \has_filter( 'query', $filter ), 'The one-shot query filter must be removed.' );
			$currentSuppressErrors = $wpdb->suppress_errors( $previousSuppressErrors );
			$this->assertSame(
				$previousSuppressErrors,
				$currentSuppressErrors,
				'The wpdb error-suppression state must be restored.'
			);
			$this->assertProbeTableAbsentRaw( $probeTable );
		}
		finally {
			$this->dropProbeTable( $probeTable, 'Fault-test restoration' );
		}

		return $diagnostics ?? [];
	}

	/**
	 * @param array<string,array<string,string>> $diagnostics
	 * @return array<string,array<string,string>>
	 */
	private function diagnosticFailures( array $diagnostics ) :array {
		return \array_filter(
			$diagnostics,
			static fn( array $diagnostic ) :bool => ( $diagnostic[ 'status' ] ?? '' ) !== 'schema_sql_valid'
		);
	}

	/**
	 * @param array<string,array<string,string>> $diagnostics
	 * @param array<string,array<string,string>> $failures
	 */
	private function assertDiagnosticsSuccessful( array $diagnostics, array $failures ) :void {
		$this->assertDiagnosticsHaveExactKeys( $diagnostics );
		$this->assertCount(
			0,
			$failures,
			"Every schema diagnostic must have status schema_sql_valid.\n".$this->formatFailureContexts( $failures )
		);
	}

	/**
	 * @param array<string,array<string,string>> $diagnostics
	 */
	private function assertDiagnosticsHaveExactKeys( array $diagnostics ) :void {
		$this->assertSame(
			\array_keys( DbCon::MAP ),
			\array_keys( $diagnostics ),
			'Diagnostics must contain exactly one row for every DbCon::MAP key in map order.'
		);
	}

	/**
	 * @param array<string,array<string,string>> $diagnostics
	 * @param array<string,array<string,string>> $failures
	 */
	private function formatDiagnosticOutput( string $probeTable, array $diagnostics, array $failures ) :string {
		$output = "\n\n=== DB TABLE SCHEMA SQL VALIDITY DIAGNOSTICS ===\n";
		$output .= "Disposable probe: {$probeTable}\n";
		$output .= 'Total schemas: '.\count( $diagnostics )."\n";
		$output .= 'Valid SQL: '.( \count( $diagnostics ) - \count( $failures ) )."\n";
		$output .= 'Invalid/error: '.\count( $failures )."\n";
		if ( !empty( $failures ) ) {
			$output .= $this->formatFailureContexts( $failures )."\n";
		}
		return $output."=== END DIAGNOSTICS ===\n";
	}

	/**
	 * @param array<string,array<string,string>> $failures
	 */
	private function formatFailureContexts( array $failures ) :string {
		$lines = [];
		foreach ( $failures as $key => $failure ) {
			$context = [ $key.': '.( $failure[ 'status' ] ?? 'missing_status' ) ];
			foreach ( [ 'source_table', 'mysql_error', 'error', 'cleanup_error', 'sql' ] as $field ) {
				if ( !empty( $failure[ $field ] ) ) {
					$context[] = $field.'='.$this->compactSnippet( $failure[ $field ] );
				}
			}
			$lines[] = \implode( '; ', $context );
		}
		return \implode( "\n", $lines );
	}

	private function assertProbeTableAbsentRaw( string $probeTable ) :void {
		try {
			$this->requireProbeTableAbsentRaw( $probeTable );
			$this->addToAssertionCount( 2 );
		}
		catch ( \RuntimeException $e ) {
			$this->fail( $e->getMessage() );
		}
	}

	private function requireProbeTableAbsentRaw( string $probeTable ) :void {
		global $wpdb;

		$wpdb->last_error = '';
		$found = $wpdb->get_var( $wpdb->prepare(
			'SHOW TABLES LIKE %s',
			$wpdb->esc_like( $probeTable )
		) );
		if ( $wpdb->last_error !== '' ) {
			throw new \RuntimeException( 'Raw probe-table absence check failed: '.$wpdb->last_error );
		}
		if ( $found !== null ) {
			throw new \RuntimeException( "Disposable probe table {$probeTable} remains after cleanup." );
		}
	}

	/**
	 * Directly test that column names with MySQL reserved words are properly handled.
	 * @group diagnostics
	 */
	public function test_reserved_word_column_detection() {
		if ( !$this->isVerbose() ) {
			$this->markTestSkipped( 'Reserved-word diagnostics disabled. Set SHIELD_TEST_VERBOSE=1 to run this diagnostic test.' );
		}

		$mysqlReservedWords = [
			'event', 'condition', 'constraint', 'default', 'describe', 'distinct',
			'float', 'foreign', 'function', 'grant', 'group', 'having', 'if', 'in',
			'index', 'inner', 'insert', 'int', 'integer', 'interval', 'into', 'is',
			'join', 'key', 'keys', 'kill', 'leave', 'left', 'like', 'limit', 'lock',
			'long', 'loop', 'match', 'natural', 'not', 'null', 'on', 'option', 'or',
			'order', 'out', 'outer', 'primary', 'procedure', 'range', 'read',
			'references', 'release', 'rename', 'repeat', 'replace', 'require',
			'return', 'revoke', 'right', 'schema', 'select', 'set', 'show', 'signal',
			'table', 'then', 'to', 'trigger', 'unique', 'unlock', 'update', 'usage',
			'use', 'using', 'values', 'when', 'where', 'while', 'with', 'write',
		];

		$con = $this->requireController();
		$reservedWordColumns = [];

		foreach ( \array_keys( DbCon::MAP ) as $dbKey ) {
			try {
				$handler = $con->db_con->load( $dbKey );
				if ( empty( $handler ) ) {
					continue;
				}
				$schema = $handler->getTableSchema();
				foreach ( $schema->getColumnNames() as $colName ) {
					if ( \in_array( \strtolower( $colName ), $mysqlReservedWords, true ) ) {
						$reservedWordColumns[] = "{$dbKey}.{$colName}";
					}
				}
			}
			catch ( \Exception $e ) {
			}
		}

		$msg = empty( $reservedWordColumns )
			? ''
			: 'Columns using MySQL reserved words (need backtick quoting): '.\implode( ', ', $reservedWordColumns );

		\fwrite( STDERR, "\n=== RESERVED WORD CHECK ===\n{$msg}\n=== END ===\n" );
		$this->assertIsArray( $reservedWordColumns );
	}
}
