<?php declare( strict_types=1 );

namespace FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\DBs;

use FernleafSystems\Wordpress\Plugin\Shield\Controller\Database\DbCon;
use FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\ShieldIntegrationTestCase;

/**
 * Diagnostic tests for the SQL generated by Shield's database schemas.
 */
class DbCreateTableDiagnosticTest extends ShieldIntegrationTestCase {

	/**
	 * Build every handler's CREATE TABLE SQL, redirect it to a unique disposable
	 * probe table, and report whether MySQL accepts that schema SQL.
	 *
	 * @group diagnostics
	 * @group database-transaction-exception
	 */
	public function test_diagnose_table_creation_failures() {
		if ( !$this->isVerbose() ) {
			$this->markTestSkipped( 'DB diagnostics disabled. Set SHIELD_TEST_VERBOSE=1 to run this diagnostic test.' );
		}

		$con = $this->requireController();
		global $wpdb;
		$probeTable = $wpdb->prefix.'shield_schema_probe_'.\substr(
			\sha1( __CLASS__.\microtime( true ).\getmypid() ),
			0,
			12
		);
		$diagnostics = [];

		$this->runWithPersistentDatabaseMutation(
			function () use ( $con, $wpdb, $probeTable, &$diagnostics ) :void {
				$dbDefs = $con->cfg->configuration->databases[ 'tables' ];
				foreach ( DbCon::MAP as $dbKey => $dbSpec ) {
					try {
						$dbDef = $dbDefs[ $dbKey ];
						$dbDef[ 'table_prefix' ] = $con->getPluginPrefix( '_' );
						$handlerClass = $dbSpec[ 'handler_class' ];
						$handler = new $handlerClass( $dbDef );
						$schema = $handler->getTableSchema();
						$createSQL = $schema->buildCreate();
						$probeSQL = \preg_replace(
							'/CREATE TABLE IF NOT EXISTS\s+`'.\preg_quote( $schema->table, '/' ).'`/i',
							"CREATE TABLE IF NOT EXISTS `{$probeTable}`",
							$createSQL,
							1,
							$replacementCount
						);
						if ( $replacementCount !== 1 || !\is_string( $probeSQL ) ) {
							throw new \RuntimeException( 'Could not redirect CREATE TABLE SQL to the disposable probe.' );
						}

						$wpdb->query( "DROP TABLE IF EXISTS `{$probeTable}`" );
						$wpdb->last_error = '';
						$previousSuppressErrors = $wpdb->suppress_errors( true );
						try {
							$result = $wpdb->query( $probeSQL );
							$mysqlError = $wpdb->last_error;
						}
						finally {
							$wpdb->suppress_errors( $previousSuppressErrors );
						}

						$diagnostics[ $dbKey ] = [
							'status'       => $result === false ? 'schema_sql_invalid' : 'schema_sql_valid',
							'source_table' => $schema->table,
							'probe_table'  => $probeTable,
							'sql'          => $probeSQL,
							'mysql_error'  => $mysqlError,
						];
					}
					catch ( \Throwable $e ) {
						$diagnostics[ $dbKey ] = [
							'status' => 'diagnostic_exception',
							'error'  => $e->getMessage(),
						];
					}
					finally {
						$wpdb->query( "DROP TABLE IF EXISTS `{$probeTable}`" );
					}
				}

				$failures = \array_filter(
					$diagnostics,
					static fn( array $diagnostic ) :bool => $diagnostic[ 'status' ] !== 'schema_sql_valid'
				);
				$output = "\n\n=== DB TABLE SCHEMA SQL VALIDITY DIAGNOSTICS ===\n";
				$output .= "Disposable probe: {$probeTable}\n";
				$output .= "Total schemas: ".\count( $diagnostics )."\n";
				$output .= "Valid SQL: ".( \count( $diagnostics ) - \count( $failures ) )."\n";
				$output .= "Invalid/error: ".\count( $failures )."\n\n";

				foreach ( $failures as $key => $diagnostic ) {
					$output .= "--- {$key} ---\n";
					$output .= "  Status: {$diagnostic['status']}\n";
					if ( isset( $diagnostic[ 'source_table' ] ) ) {
						$output .= "  Source table: {$diagnostic['source_table']}\n";
					}
					if ( !empty( $diagnostic[ 'mysql_error' ] ) ) {
						$output .= "  MySQL error: {$diagnostic['mysql_error']}\n";
					}
					if ( isset( $diagnostic[ 'sql' ] ) ) {
						$output .= "  Probe SQL:\n    ".\str_replace( "\n", "\n    ", $diagnostic[ 'sql' ] )."\n";
					}
					if ( isset( $diagnostic[ 'error' ] ) ) {
						$output .= "  Exception: {$diagnostic['error']}\n";
					}
					$output .= "\n";
				}
				$output .= "=== END DIAGNOSTICS ===\n";
				\fwrite( STDERR, $output );
			},
			function () use ( $wpdb, $probeTable ) :void {
				if ( $wpdb->query( "DROP TABLE IF EXISTS `{$probeTable}`" ) === false ) {
					throw new \RuntimeException( 'Failed to remove the disposable DB schema probe table.' );
				}
			}
		);

		$this->assertNotEmpty( $diagnostics, 'Should have processed all handlers' );
	}

	/**
	 * Directly test that column names with MySQL reserved words are properly handled.
	 * @group diagnostics
	 */
	public function test_reserved_word_column_detection() {
		if ( !$this->isVerbose() ) {
			$this->markTestSkipped( 'Reserved-word diagnostics disabled. Set SHIELD_TEST_VERBOSE=1 to run this diagnostic test.' );
		}

		$mysqlReservedWords = [
			'event', 'condition', 'constraint', 'default', 'describe', 'distinct',
			'float', 'foreign', 'function', 'grant', 'group', 'having', 'if', 'in',
			'index', 'inner', 'insert', 'int', 'integer', 'interval', 'into', 'is',
			'join', 'key', 'keys', 'kill', 'leave', 'left', 'like', 'limit', 'lock',
			'long', 'loop', 'match', 'natural', 'not', 'null', 'on', 'option', 'or',
			'order', 'out', 'outer', 'primary', 'procedure', 'range', 'read',
			'references', 'release', 'rename', 'repeat', 'replace', 'require',
			'return', 'revoke', 'right', 'schema', 'select', 'set', 'show', 'signal',
			'table', 'then', 'to', 'trigger', 'unique', 'unlock', 'update', 'usage',
			'use', 'using', 'values', 'when', 'where', 'while', 'with', 'write',
		];

		$con = $this->requireController();
		$reservedWordColumns = [];

		foreach ( \array_keys( DbCon::MAP ) as $dbKey ) {
			try {
				$handler = $con->db_con->load( $dbKey );
				if ( empty( $handler ) ) {
					continue;
				}
				$schema = $handler->getTableSchema();
				foreach ( $schema->getColumnNames() as $colName ) {
					if ( \in_array( \strtolower( $colName ), $mysqlReservedWords, true ) ) {
						$reservedWordColumns[] = "{$dbKey}.{$colName}";
					}
				}
			}
			catch ( \Exception $e ) {
			}
		}

		$msg = empty( $reservedWordColumns )
			? ''
			: 'Columns using MySQL reserved words (need backtick quoting): '.\implode( ', ', $reservedWordColumns );

		\fwrite( STDERR, "\n=== RESERVED WORD CHECK ===\n{$msg}\n=== END ===\n" );
		$this->assertIsArray( $reservedWordColumns );
	}
}
