<?php declare( strict_types=1 );

namespace FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\Email;

use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Email\AdminLoginNotification;
use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Email\BackupCodeUsed;
use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Email\FirewallBlockAlert;
use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Reports\Contexts\EmailReport;
use FernleafSystems\Wordpress\Plugin\Shield\Modules\Plugin\Lib\Reporting\Constants;
use FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\Email\Support\BuildReportEmailFixture;
use FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\Email\Support\PlainTextEmailAssertions;
use FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\ShieldIntegrationTestCase;
use FernleafSystems\Wordpress\Plugin\Shield\Utilities\Tool\ConvertHtmlToText;

class RenderedEmailPlainTextContractTest extends ShieldIntegrationTestCase {

	use BuildReportEmailFixture;
	use PlainTextEmailAssertions;

	public function test_admin_login_notification_render_converts_cleanly() :void {
		$html = $this->requireController()->action_router->render( AdminLoginNotification::class, [
			'role_name'  => 'Administrator+',
			'home_url'   => 'https://example.com',
			'username'   => 'managedadmin',
			'user_email' => 'managedadmin@example.com',
			'ip'         => '198.51.100.23',
		] );

		$text = ( new ConvertHtmlToText() )->run( $html );

		$this->assertPlainTextOutputHealthy( $text, 'Admin render conversion' );
		$this->assertContainsTokens( $text, [
			'Administrator+ login',
			'managedadmin@example.com',
			'Configure security email recipient',
		], 'Admin render conversion' );
		$this->assertTokensAppearInOrder( $text, [
			'Details for this user are below:',
			'Site URL: https://example.com',
			'Username: managedadmin',
			'Email: managedadmin@example.com',
			'IP Address: 198.51.100.23',
		], 'Admin render order' );
	}

	public function test_backup_code_used_render_converts_cleanly_with_user_footer() :void {
		$html = $this->requireController()->action_router->render( BackupCodeUsed::class, [
			'home_url' => 'https://example.com',
			'username' => 'mfauser',
			'ip'       => '203.0.113.87',
		] );

		$text = ( new ConvertHtmlToText() )->run( $html );

		$this->assertPlainTextOutputHealthy( $text, 'Backup code render conversion' );
		$this->assertContainsTokens( $text, [
			'Backup Login code was just used',
			'Login Details',
			'Username: mfauser',
		], 'Backup code render conversion' );
		$this->assertStringNotContainsString( 'Configure security email recipient', $text );
	}

	public function test_firewall_block_alert_render_converts_request_details_and_links() :void {
		$con = $this->requireController();
		$con->this_req->path = '/wp-login.php';

		$html = $con->action_router->render( FirewallBlockAlert::class, [
			'ip'         => '203.0.113.10',
			'block_meta' => [
				'firewall_rule_name'  => 'SQL Injection',
				'match_pattern'       => 'select%20from',
				'match_request_param' => 'query',
				'match_request_value' => 'select from wp_users',
			],
		] );

		$text = ( new ConvertHtmlToText() )->run( $html );

		$this->assertPlainTextOutputHealthy( $text, 'Firewall render conversion' );
		$this->assertContainsTokens( $text, [
			'Request Details:',
			'Visitor IP Address',
			'SQL Injection',
			'IP Address Lookup (https://',
			'Configure Firewall Block alert emails',
		], 'Firewall render conversion' );
		$this->assertTokensAppearInOrder( $text, [
			'Request Details:',
			'Visitor IP Address',
			'Firewall Rule',
			'Firewall Pattern',
			'Request Path',
			'Parameter Name',
			'Parameter Value',
		], 'Firewall render detail order' );
	}

	public function test_report_render_converts_real_report_html_with_section_contracts() :void {
		$html = $this->requireController()->action_router->render( EmailReport::class, [
			'home_url'     => 'https://example.com',
			'reports'      => [ $this->buildReportFixture( Constants::REPORT_TYPE_ALERT ) ],
			'detail_level' => 'detailed',
		] );

		$text = ( new ConvertHtmlToText() )->run( $html );

		$this->assertPlainTextOutputHealthy( $text, 'Report render conversion' );
		$this->assertContainsTokens( $text, [
			'Security Report',
			'Scan Issues',
			'2 new',
			'IP Offenses',
			'Changes',
			'Malware Scan',
			'... and 2 more',
			'Automatic Repairs',
			'Security Stats',
			'Login Failures',
			'Plugins',
			'Users',
			'View Full Report',
			'Generated by Shield Security',
		], 'Report render conversion' );
		$this->assertContainsTokens( $text, [
			'/wp-content/plugins/bad-plugin/malware.php',
			'/wp-content/uploads/suspicious/payload.js',
			'https://example.com/plugin/example-plugin',
		], 'Report detail preservation' );
		$this->assertTokensAppearInOrder( $text, [
			'Security Report',
			'Latest Scan Results',
			'Malware Scan',
			'... and 2 more',
			'Scan File Repairs',
			'Automatic Repairs',
			'Statistics',
			'Security Stats',
			'IP Offenses',
			'Login Failures',
			'Changes',
			'Plugins',
			'Users',
			'View Full Report',
		], 'Report section order' );
	}
}
