<?php declare( strict_types=1 );

namespace FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\Email;

use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Email\BackupCodeUsed;
use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Email\FirewallBlockAlert;
use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Email\InstantAlerts\EmailInstantAlertAdminLogin;
use FernleafSystems\Wordpress\Plugin\Shield\ActionRouter\Actions\Render\Components\Reports\Contexts\{
	EmailReportAlert,
	EmailReportInfo
};
use FernleafSystems\Wordpress\Plugin\Shield\Modules\Plugin\Lib\Reporting\Constants;
use FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\Email\Support\BuildReportEmailFixture;
use FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\Email\Support\PlainTextEmailAssertions;
use FernleafSystems\Wordpress\Plugin\Shield\Tests\Integration\ShieldIntegrationTestCase;
use FernleafSystems\Wordpress\Plugin\Shield\Utilities\Tool\ConvertHtmlToText;

class RenderedEmailPlainTextContractTest extends ShieldIntegrationTestCase {

	use BuildReportEmailFixture;
	use PlainTextEmailAssertions;

	public function test_admin_login_notification_render_converts_cleanly() :void {
		$html = $this->requireController()->action_router->render( EmailInstantAlertAdminLogin::class, [
			'alert_data' => [
				'admin_login' => [
					'role_name'  => 'Administrator+',
					'username'   => 'managedadmin',
					'user_email' => 'managedadmin@example.com',
					'ip'         => '198.51.100.23',
				]
			],
		] );

		$text = ( new ConvertHtmlToText() )->run( $html );

		$this->assertPlainTextOutputHealthy( $text, 'Admin render conversion' );
		$this->assertContainsTokens( $text, [
			'Administrator+ login',
			'managedadmin@example.com',
			'Configure security email recipient',
		], 'Admin render conversion' );
		$this->assertTokensAppearInOrder( $text, [
			'Site Address (URL): https://example.com',
			'As requested, Shield is notifying you of a successful Administrator+ login',
			'Important: This user may now be subject to additional Two-Factor Authentication before completing their login.',
			'Login Details',
			'Username: managedadmin',
			'Email: managedadmin@example.com',
			'IP Address: 198.51.100.23',
		], 'Admin render order' );
	}

	public function test_backup_code_used_render_converts_cleanly_with_user_footer() :void {
		$html = $this->requireController()->action_router->render( BackupCodeUsed::class, [
			'home_url' => 'https://example.com',
			'username' => 'mfauser',
			'ip'       => '203.0.113.87',
		] );

		$text = ( new ConvertHtmlToText() )->run( $html );

		$this->assertPlainTextOutputHealthy( $text, 'Backup code render conversion' );
		$this->assertContainsTokens( $text, [
			'Backup Login code was just used',
			'Login Details',
			'Username: mfauser',
		], 'Backup code render conversion' );
		$this->assertStringNotContainsString( 'Configure security email recipient', $text );
	}

	public function test_firewall_block_alert_render_converts_request_details_and_links() :void {
		$con = $this->requireController();
		$con->this_req->path = '/wp-login.php';

		$html = $con->action_router->render( FirewallBlockAlert::class, [
			'ip'         => '203.0.113.10',
			'block_meta' => [
				'firewall_rule_name'  => 'SQL Injection',
				'match_pattern'       => 'select%20from',
				'match_request_param' => 'query',
				'match_request_value' => 'select from wp_users',
			],
		] );

		$text = ( new ConvertHtmlToText() )->run( $html );

		$this->assertPlainTextOutputHealthy( $text, 'Firewall render conversion' );
		$this->assertContainsTokens( $text, [
			'Request Details:',
			'Visitor IP Address',
			'SQL Injection',
			'IP Address Lookup',
			'Configure Firewall Block alert emails',
		], 'Firewall render conversion' );
		$this->assertTokensAppearInOrder( $text, [
			'Request Details:',
			'Visitor IP Address',
			'Firewall Rule',
			'Firewall Pattern',
			'Request Path',
			'Parameter Name',
			'Parameter Value',
		], 'Firewall render detail order' );
	}

	public function test_alert_report_render_converts_real_report_html_with_alert_only_contracts() :void {
		$html = $this->requireController()->action_router->render( EmailReportAlert::class, [
			'home_url'     => 'https://example.com',
			'report'       => $this->buildReportFixture( Constants::REPORT_TYPE_ALERT ),
			'detail_level' => 'detailed',
		] );

		$text = ( new ConvertHtmlToText() )->run( $html );

		$this->assertPlainTextOutputHealthy( $text, 'Alert report render conversion' );
		$this->assertContainsTokens( $text, [
			'March 10, 2024',
			'Security Alert',
			'New Issues',
			'Still Outstanding',
			'Current Critical Issues',
			'Malware Scan',
			'Vulnerability Scan',
			'Review Scan Results',
			'View Full Report',
			'Generated by Shield Security',
		], 'Alert report render conversion' );
		$this->assertContainsTokens( $text, [
			'/wp-content/plugins/bad-plugin/malware.php',
			'/wp-content/uploads/suspicious/payload.js',
			'/wp-content/uploads/cache/legacy-shell.php',
		], 'Alert report detail preservation' );
		$this->assertTokensAppearInOrder( $text, [
			'New Issues',
			'Malware Scan',
			'Still Outstanding',
			'/wp-content/uploads/cache/legacy-shell.php',
			'Vulnerability Scan',
			'View Full Report',
		], 'Alert report section order' );
		$this->assertStringNotContainsString( 'Statistics', $text );
		$this->assertStringNotContainsString( 'Changes', $text );
		$this->assertStringNotContainsString( 'Automatic Repairs', $text );
	}

	public function test_info_report_render_converts_real_report_html_with_status_headline() :void {
		$html = $this->requireController()->action_router->render( EmailReportInfo::class, [
			'home_url'     => 'https://example.com',
			'report'       => $this->buildReportFixture( Constants::REPORT_TYPE_INFO ),
			'detail_level' => 'detailed',
		] );

		$text = ( new ConvertHtmlToText() )->run( $html );

		$this->assertPlainTextOutputHealthy( $text, 'Info report render conversion' );
		$this->assertContainsTokens( $text, [
			'March 10, 2024',
			'Security Report',
			'2 issues need attention',
			'Alert Status',
			'Security Posture',
			'Scan Status',
			'Latest Scan Results',
			'Scan File Repairs',
			'Statistics',
			'Changes',
			'View Full Report',
			'Generated by Shield Security',
		], 'Info report render conversion' );
		$this->assertTokensAppearInOrder( $text, [
			'2 issues need attention',
			'Alert Status',
			'Security Posture',
			'Scan Status',
			'Latest Scan Results',
			'Malware Scan',
			'Scan File Repairs',
			'Automatic Repairs',
			'Statistics',
			'Security Stats',
			'Changes',
			'Plugins',
			'Users',
			'View Full Report',
		], 'Info report section order' );
	}
}
