<?php declare( strict_types=1 );

/**
 * AUTO-GENERATED Translation Declaration File
 * 
 * This file is automatically generated from plugin.json
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * 
 * Generated on: 2025-09-24 12:58:40
 * Total strings: 478
 * 
 * Usage: Run php extract_json_strings_for_translation.php to regenerate
 */

if ( false ) { // This ensures the code is never executed but is parsed for translation

	// Section Titles
	__( 'Security Admin Restriction Settings', 'wp-simple-firewall' ); // config_spec.sections.1.title
	__( 'Security Admin Restriction Zones', 'wp-simple-firewall' ); // config_spec.sections.2.title
	__( 'WordPress Activity', 'wp-simple-firewall' ); // config_spec.sections.3.title
	__( 'Automatic Bot Comment SPAM Protection Filter', 'wp-simple-firewall' ); // config_spec.sections.5.title
	__( 'Human Comment SPAM Protection', 'wp-simple-firewall' ); // config_spec.sections.6.title
	__( 'Common Settings For All SPAM Scanning', 'wp-simple-firewall' ); // config_spec.sections.7.title
	__( 'Request Firewall Options', 'wp-simple-firewall' ); // config_spec.sections.8.title
	__( 'WordPress System Lockdown', 'wp-simple-firewall' ); // config_spec.sections.9.title
	__( 'WordPress Obscurity Options', 'wp-simple-firewall' ); // config_spec.sections.11.title
	__( 'Automatic IP Black List', 'wp-simple-firewall' ); // config_spec.sections.15.title
	__( 'Identify Common Bot Behaviours', 'wp-simple-firewall' ); // config_spec.sections.18.title
	__( 'Enable Module: IP Manager', 'wp-simple-firewall' ); // config_spec.sections.19.title
	__( 'Brute Force Login Guard', 'wp-simple-firewall' ); // config_spec.sections.20.title
	__( 'User Session Management', 'wp-simple-firewall' ); // config_spec.sections.21.title
	__( 'Multi-Factor Authentication', 'wp-simple-firewall' ); // config_spec.sections.22.title
	__( 'Email Two-Factor Authentication', 'wp-simple-firewall' ); // config_spec.sections.23.title
	__( 'One-Time Passwords', 'wp-simple-firewall' ); // config_spec.sections.24.title
	__( 'Hardware 2-Factor Authentication', 'wp-simple-firewall' ); // config_spec.sections.25.title
	__( 'Hide WP Login Page', 'wp-simple-firewall' ); // config_spec.sections.26.title
	__( 'Advanced Security Headers', 'wp-simple-firewall' ); // config_spec.sections.31.title
	__( 'Shield White Label', 'wp-simple-firewall' ); // config_spec.sections.33.title
	__( 'Global Plugin Security Options', 'wp-simple-firewall' ); // config_spec.sections.34.title
	__( 'Automatic And Manual User Suspension', 'wp-simple-firewall' ); // config_spec.sections.37.title
	__( 'Enable Module: User Management', 'wp-simple-firewall' ); // config_spec.sections.38.title

	// Section Short Titles
	__( 'Security Admin Settings', 'wp-simple-firewall' ); // config_spec.sections.1.title_short
	__( 'Access Restriction Zones', 'wp-simple-firewall' ); // config_spec.sections.2.title_short
	__( 'WP Activity', 'wp-simple-firewall' ); // config_spec.sections.3.title_short
	__( 'Request Logging', 'wp-simple-firewall' ); // config_spec.sections.4.title_short
	__( 'Bot SPAM', 'wp-simple-firewall' ); // config_spec.sections.5.title_short
	__( 'Human SPAM', 'wp-simple-firewall' ); // config_spec.sections.6.title_short
	__( 'Common Settings', 'wp-simple-firewall' ); // config_spec.sections.7.title_short
	__( 'Request Firewall', 'wp-simple-firewall' ); // config_spec.sections.8.title_short
	__( 'Rate Limiting', 'wp-simple-firewall' ); // config_spec.sections.10.title_short
	__( 'File Guard', 'wp-simple-firewall' ); // config_spec.sections.12.title_short
	__( 'Scan Options', 'wp-simple-firewall' ); // config_spec.sections.14.title_short
	__( 'Auto IP Blocking Rules', 'wp-simple-firewall' ); // config_spec.sections.15.title_short
	__( 'Bot Behaviours', 'wp-simple-firewall' ); // config_spec.sections.18.title_short
	__( 'Disable Module', 'wp-simple-firewall' ); // config_spec.sections.38.title_short
	__( 'Brute Force', 'wp-simple-firewall' ); // config_spec.sections.20.title_short
	__( '2-Factor Auth', 'wp-simple-firewall' ); // config_spec.sections.22.title_short
	__( '2FA - Email', 'wp-simple-firewall' ); // config_spec.sections.23.title_short
	__( '2FA - Hardware', 'wp-simple-firewall' ); // config_spec.sections.25.title_short
	__( 'Hide Login Page', 'wp-simple-firewall' ); // config_spec.sections.26.title_short
	__( 'Plugin Defaults', 'wp-simple-firewall' ); // config_spec.sections.28.title_short
	__( 'Instant Alerts', 'wp-simple-firewall' ); // config_spec.sections.30.title_short
	__( 'Security Headers', 'wp-simple-firewall' ); // config_spec.sections.31.title_short
	__( 'White Label', 'wp-simple-firewall' ); // config_spec.sections.33.title_short
	__( 'Disable Shield', 'wp-simple-firewall' ); // config_spec.sections.34.title_short
	__( 'Password Policies', 'wp-simple-firewall' ); // config_spec.sections.35.title_short
	__( 'User Registration', 'wp-simple-firewall' ); // config_spec.sections.36.title_short
	__( 'User Suspension', 'wp-simple-firewall' ); // config_spec.sections.37.title_short
	__( 'SPAM Detection', 'wp-simple-firewall' ); // config_spec.sections.40.title_short
	__( 'User Forms Bot Detection', 'wp-simple-firewall' ); // config_spec.sections.41.title_short

	// Module Names & Taglines
	__( 'Security Admin', 'wp-simple-firewall' ); // config_spec.modules.admin_access_restriction.name
	__( 'Security admin allows you to restrict access to the security plugin itself.', 'wp-simple-firewall' ); // config_spec.modules.admin_access_restriction.tagline
	__( 'Track All Site Activity: Who, What, When and Where', 'wp-simple-firewall' ); // config_spec.modules.audit_trail.tagline
	__( 'Block comment SPAM while retaining your privacy', 'wp-simple-firewall' ); // config_spec.modules.comments_filter.tagline
	__( 'Automatically block malicious HTTP requests and data sent to your site', 'wp-simple-firewall' ); // config_spec.modules.firewall.tagline
	__( 'Automatically detect & repair vulnerable and suspicious files, plugins and themes.', 'wp-simple-firewall' ); // config_spec.modules.hack_protect.tagline
	__( 'Detect malicious bots and visitors, and block them from accessing the site.', 'wp-simple-firewall' ); // config_spec.modules.ips.tagline
	__( 'Login Protection', 'wp-simple-firewall' ); // config_spec.modules.login_protect.name
	__( 'Add protections to your WordPress login forms and protect user accounts with 2-Factor Authentication.', 'wp-simple-firewall' ); // config_spec.modules.login_protect.tagline
	__( 'General plugin settings that apply across the entire plugin operation.', 'wp-simple-firewall' ); // config_spec.modules.plugin.tagline
	__( 'Control user sessions, duration, timeouts and account sharing.', 'wp-simple-firewall' ); // config_spec.modules.user_management.tagline

	// Other Translatable Strings
	__( 'Love it? Rate This Plugin &#10025;', 'wp-simple-firewall' ); // plugin_meta.rate.name
	__( 'Security Dashboard', 'wp-simple-firewall' ); // action_links.add.0.name
	__( 'Go To Security Dashboard', 'wp-simple-firewall' ); // action_links.add.0.title
	__( '&uarr; Go Pro &uarr;', 'wp-simple-firewall' ); // action_links.add.1.name
	__( 'Get All PRO Security Features', 'wp-simple-firewall' ); // action_links.add.1.title
	__( 'Vulnerability Scanner', 'wp-simple-firewall' ); // config_spec.options.53.name
	__( 'Security Admin Access PIN', 'wp-simple-firewall' ); // config_spec.options.12.name
	__( 'Careful: If you forget this, you could potentially lock yourself out from using this plugin.', 'wp-simple-firewall' ); // config_spec.options.12.description
	__( 'Security Admin Timeout', 'wp-simple-firewall' ); // config_spec.options.13.name
	__( 'Specify An Automatic Timeout Interval For Security Admin Access', 'wp-simple-firewall' ); // config_spec.options.13.summary
	__( 'This will automatically expire your Security Admin Session. Does not apply until you enter the access PIN again. Default: 60 minutes.', 'wp-simple-firewall' ); // config_spec.options.13.description
	__( 'Security Admins', 'wp-simple-firewall' ); // config_spec.options.14.name
	__( 'Persistent Security Admins', 'wp-simple-firewall' ); // config_spec.options.14.summary
	__( 'All emails, usernames, or user IDs entered here will always be Security Admins.', 'wp-simple-firewall' ); // config_spec.options.14.description
	__( 'Allow Email Override', 'wp-simple-firewall' ); // config_spec.options.15.name
	__( 'Allow Email Override Of Admin Access Restrictions', 'wp-simple-firewall' ); // config_spec.options.15.summary
	__( 'Allow the use of verification emails to override and switch off the Security Admin restrictions.', 'wp-simple-firewall' ); // config_spec.options.15.description
	__( 'WordPress Options', 'wp-simple-firewall' ); // config_spec.options.16.name
	__( 'Restrict Access To Certain WordPress Admin Options', 'wp-simple-firewall' ); // config_spec.options.16.summary
	__( 'Careful: This will restrict the ability of WordPress administrators from changing key WordPress settings.', 'wp-simple-firewall' ); // config_spec.options.16.description
	__( 'Admin Users', 'wp-simple-firewall' ); // config_spec.options.17.name
	__( 'Careful: This will restrict the ability of WordPress administrators from creating, modifying or promoting other administrators.', 'wp-simple-firewall' ); // config_spec.options.17.description
	__( 'Restrict Access To Key WordPress Plugin Actions', 'wp-simple-firewall' ); // config_spec.options.18.summary
	__( "Careful: This will restrict access to plugin installation, update, activation and deletion. Note: Selecting 'Activate' will also restrict all other options.", 'wp-simple-firewall' ); // config_spec.options.18.description
	__( 'Restrict Access To WordPress Theme Actions', 'wp-simple-firewall' ); // config_spec.options.19.summary
	__( 'Careful: This will restrict access to theme installation, update, activation and deletion.', 'wp-simple-firewall' ); // config_spec.options.19.description
	__( 'Restrict Access To Key WordPress Posts And Pages Actions', 'wp-simple-firewall' ); // config_spec.options.20.summary
	__( 'Enable White Label', 'wp-simple-firewall' ); // config_spec.options.21.name
	__( 'Activate Your White Label Settings', 'wp-simple-firewall' ); // config_spec.options.21.summary
	__( 'Plugin Name', 'wp-simple-firewall' ); // config_spec.options.22.name
	__( 'The Name Of The Plugin', 'wp-simple-firewall' ); // config_spec.options.22.summary
	__( 'The Name Of The Plugin.', 'wp-simple-firewall' ); // config_spec.options.22.description
	__( 'Menu Title', 'wp-simple-firewall' ); // config_spec.options.23.name
	__( 'The Main Menu Title Of The Plugin', 'wp-simple-firewall' ); // config_spec.options.23.summary
	__( 'The Main Menu Title Of The Plugin. If left empty, the Plugin Name will be used.', 'wp-simple-firewall' ); // config_spec.options.23.description
	__( 'Company Name', 'wp-simple-firewall' ); // config_spec.options.24.name
	__( 'The Name Of Your Company', 'wp-simple-firewall' ); // config_spec.options.24.summary
	__( 'Provide the name of your company.', 'wp-simple-firewall' ); // config_spec.options.24.description
	__( 'Plugin Tag Line', 'wp-simple-firewall' ); // config_spec.options.25.name
	__( 'The Tag Line Of The Plugin', 'wp-simple-firewall' ); // config_spec.options.25.summary
	__( 'The Tag Line Of The Plugin.', 'wp-simple-firewall' ); // config_spec.options.25.description
	__( 'Home URL', 'wp-simple-firewall' ); // config_spec.options.26.name
	__( 'Plugin Home Page URL', 'wp-simple-firewall' ); // config_spec.options.26.summary
	__( "When a user clicks the home link for this plugin, this is where they'll be directed.", 'wp-simple-firewall' ); // config_spec.options.26.description
	__( 'Menu Icon', 'wp-simple-firewall' ); // config_spec.options.27.name
	__( 'Menu Icon URL', 'wp-simple-firewall' ); // config_spec.options.27.summary
	__( 'The URL of the icon displayed in the menu.', 'wp-simple-firewall' ); // config_spec.options.27.description
	__( 'Plugin Badge Logo', 'wp-simple-firewall' ); // config_spec.options.28.name
	__( 'Plugin Badge Logo URL', 'wp-simple-firewall' ); // config_spec.options.28.summary
	__( 'The URL of the logo displayed in the main dashboard. Should be 128x128px', 'wp-simple-firewall' ); // config_spec.options.29.description
	__( 'Dashboard and 2FA Logo', 'wp-simple-firewall' ); // config_spec.options.29.name
	__( 'Dashboard and 2FA Logo URL', 'wp-simple-firewall' ); // config_spec.options.29.summary
	__( 'Logging Level', 'wp-simple-firewall' ); // config_spec.options.30.name
	__( 'Logging Level For DB-Based Logs', 'wp-simple-firewall' ); // config_spec.options.30.description
	__( 'Auto Clean', 'wp-simple-firewall' ); // config_spec.options.31.name
	__( 'Enable Audit Auto Cleaning', 'wp-simple-firewall' ); // config_spec.options.31.summary
	__( 'Events older than the number of days specified will be automatically cleaned from the database', 'wp-simple-firewall' ); // config_spec.options.31.description
	__( 'Update Delay', 'wp-simple-firewall' ); // config_spec.options.32.name
	__( 'Delay Automatic Updates For Period Of Stability', 'wp-simple-firewall' ); // config_spec.options.32.summary
	__( 'Shield will delay upgrades until the new update has been available for the set number of days.', 'wp-simple-firewall' ); // config_spec.options.32.description
	__( "Use Shield's Unique silentCAPTCHA Technology", 'wp-simple-firewall' ); // config_spec.options.33.summary
	__( "Use Shield's silentCAPTCHA To Detect and Block SPAM Bots.", 'wp-simple-firewall' ); // config_spec.options.33.description
	__( 'SPAM Action', 'wp-simple-firewall' ); // config_spec.options.36.name
	__( 'How To Categorise Comments When Identified To Be SPAM', 'wp-simple-firewall' ); // config_spec.options.34.summary
	__( 'When a comment is detected as being SPAM from an automatic bot, the comment will be categorised based on this setting.', 'wp-simple-firewall' ); // config_spec.options.34.description
	__( 'Human SPAM Filter', 'wp-simple-firewall' ); // config_spec.options.35.name
	__( 'Scans the content of WordPress comments for keywords that are indicative of SPAM and marks the comment according to your preferred setting below.', 'wp-simple-firewall' ); // config_spec.options.35.description
	__( "How To Categorise Comments When Identified To Be SPAM'", 'wp-simple-firewall' ); // config_spec.options.36.summary
	__( 'When a comment is detected as being SPAM from a human commenter, the comment will be categorised based on this setting.', 'wp-simple-firewall' ); // config_spec.options.36.description
	__( 'Trusted Commenter Minimum', 'wp-simple-firewall' ); // config_spec.options.37.name
	__( 'Minimum Number Of Approved Comments Before Commenter Is Trusted', 'wp-simple-firewall' ); // config_spec.options.37.summary
	__( 'Specify how many approved comments must exist before a commenter is trusted and their comments are no longer scanned.', 'wp-simple-firewall' ); // config_spec.options.37.description
	__( 'Trusted Users', 'wp-simple-firewall' ); // config_spec.options.38.name
	__( "Don't Scan Comments For Users With The Following Roles", 'wp-simple-firewall' ); // config_spec.options.38.summary
	__( "Shield doesn't normally scan comments from logged-in or registered users. Specify user roles here that shouldn't be scanned.", 'wp-simple-firewall' ); // config_spec.options.38.description
	__( 'Comments Cooldown', 'wp-simple-firewall' ); // config_spec.options.39.name
	__( 'Prevents comment floods and ensure a minimum period before any further comments are accepted on the site.', 'wp-simple-firewall' ); // config_spec.options.39.description
	__( 'Send Email Report', 'wp-simple-firewall' ); // config_spec.options.40.name
	__( 'Send Firewall Trigger Report Email', 'wp-simple-firewall' ); // config_spec.options.40.summary
	__( 'Use with caution - if you get hit by automated bots you may send out too many emails and you could get blocked by your host.', 'wp-simple-firewall' ); // config_spec.options.40.description
	__( 'Whitelist Parameters', 'wp-simple-firewall' ); // config_spec.options.41.name
	__( 'This should be used with caution and you should only provide parameter names that you must have excluded', 'wp-simple-firewall' ); // config_spec.options.41.description
	__( 'Directory Traversals', 'wp-simple-firewall' ); // config_spec.options.42.name
	__( 'Block Directory Traversals', 'wp-simple-firewall' ); // config_spec.options.42.summary
	__( 'This will block directory traversal paths in in application parameters.', 'wp-simple-firewall' ); // config_spec.options.42.description
	__( 'SQL Queries', 'wp-simple-firewall' ); // config_spec.options.43.name
	__( 'Block SQL Queries', 'wp-simple-firewall' ); // config_spec.options.43.summary
	__( 'This will block SQL in application parameters.', 'wp-simple-firewall' ); // config_spec.options.43.description
	__( 'Field Truncation', 'wp-simple-firewall' ); // config_spec.options.44.name
	__( 'Block Field Truncation Attacks', 'wp-simple-firewall' ); // config_spec.options.44.summary
	__( 'This will block field truncation attacks in application parameters', 'wp-simple-firewall' ); // config_spec.options.44.description
	__( 'PHP Code', 'wp-simple-firewall' ); // config_spec.options.45.name
	__( 'Block PHP Code Includes', 'wp-simple-firewall' ); // config_spec.options.45.summary
	__( 'Aggressive Scan', 'wp-simple-firewall' ); // config_spec.options.46.name
	__( 'Aggressively Block Data', 'wp-simple-firewall' ); // config_spec.options.46.summary
	__( 'Employs a set of aggressive rules to detect and block malicious data submitted to your site. Warning - May cause an increase in false-positive firewall blocks.', 'wp-simple-firewall' ); // config_spec.options.46.description
	__( 'WP Core File Scanner', 'wp-simple-firewall' ); // config_spec.options.47.name
	__( 'Automatically Scans WordPress Core Files For Alterations', 'wp-simple-firewall' ); // config_spec.options.47.summary
	__( 'Compares all WordPress core files on your site against the official WordPress files. WordPress Core files should never be altered for any reason.', 'wp-simple-firewall' ); // config_spec.options.47.description
	__( 'File Scan Areas', 'wp-simple-firewall' ); // config_spec.options.48.name
	__( 'Which Files Should Be Scanned', 'wp-simple-firewall' ); // config_spec.options.48.summary
	__( 'Specific file scan areas.', 'wp-simple-firewall' ); // config_spec.options.48.description
	__( 'Auto File Repair', 'wp-simple-firewall' ); // config_spec.options.49.name
	__( 'Which Files Should Be Automatically Repaired?', 'wp-simple-firewall' ); // config_spec.options.49.summary
	__( 'When a file is modified, or malware is detected, Shield can try to repair files.', 'wp-simple-firewall' ); // config_spec.options.49.description
	__( 'File Locker', 'wp-simple-firewall' ); // config_spec.options.50.name
	__( 'Lock Files Against Tampering and Changes', 'wp-simple-firewall' ); // config_spec.options.50.summary
	__( 'As soon as changes are detected to any selected files, the contents may be examined and reverted.', 'wp-simple-firewall' ); // config_spec.options.50.description
	__( 'Scan Exclusions', 'wp-simple-firewall' ); // config_spec.options.51.name
	__( 'Scan File and Folder Exclusions', 'wp-simple-firewall' ); // config_spec.options.51.summary
	__( 'Scan File and Folder Exclusions.', 'wp-simple-firewall' ); // config_spec.options.51.description
	__( 'Abandoned Plugin Scanner', 'wp-simple-firewall' ); // config_spec.options.52.name
	__( 'Enable The Abandoned Plugin Scanner', 'wp-simple-firewall' ); // config_spec.options.52.summary
	__( "Scan your WordPress.org assets for whether they've been abandoned.", 'wp-simple-firewall' ); // config_spec.options.52.description
	__( 'Enable The Vulnerability Scanner', 'wp-simple-firewall' ); // config_spec.options.53.summary
	__( 'Scan all your WordPress assets for known security vulnerabilities.', 'wp-simple-firewall' ); // config_spec.options.53.description
	__( 'Automatic Updates', 'wp-simple-firewall' ); // config_spec.options.54.name
	__( 'Apply Updates Automatically To Vulnerable Plugins', 'wp-simple-firewall' ); // config_spec.options.54.summary
	__( 'When an update becomes available, automatically apply updates to items with known vulnerabilities.', 'wp-simple-firewall' ); // config_spec.options.54.description
	__( 'Scan Frequency', 'wp-simple-firewall' ); // config_spec.options.55.name
	__( 'Number Of Times To Automatically Scan Core Files In 24 Hours', 'wp-simple-firewall' ); // config_spec.options.55.summary
	__( 'Default: Once every 24hrs. To improve security, increase the number of scans per day.', 'wp-simple-firewall' ); // config_spec.options.55.description
	__( 'Optimise File Scans', 'wp-simple-firewall' ); // config_spec.options.56.summary
	__( 'Optimise file scans wherever possible.', 'wp-simple-firewall' ); // config_spec.options.56.description
	__( 'Show Re-Install Links', 'wp-simple-firewall' ); // config_spec.options.57.name
	__( 'Show Re-Install Links For Plugins', 'wp-simple-firewall' ); // config_spec.options.57.summary
	__( 'Show links to re-install plugins and offer re-install when activating plugins.', 'wp-simple-firewall' ); // config_spec.options.57.description
	__( 'Enable Auto-Integrations', 'wp-simple-firewall' ); // config_spec.options.66.name
	__( "Automatically Enable 3rd Party Integrations As They're Detected", 'wp-simple-firewall' ); // config_spec.options.66.summary
	__( "When switched-on, any available 3rd party integrations are enabled as soon as they're detected.", 'wp-simple-firewall' ); // config_spec.options.66.description
	__( 'Enable MainWP', 'wp-simple-firewall' ); // config_spec.options.67.name
	__( 'Enable The Built-In MainWP Extension', 'wp-simple-firewall' ); // config_spec.options.67.summary
	__( "This option will enable Shield's built-in MainWP extension for both server and client.", 'wp-simple-firewall' ); // config_spec.options.67.description
	__( 'SureSend Emails', 'wp-simple-firewall' ); // config_spec.options.68.summary
	__( 'SureSend Emails.', 'wp-simple-firewall' ); // config_spec.options.68.description
	__( 'Bot Challenge Complexity', 'wp-simple-firewall' ); // config_spec.options.69.description
	__( 'silentCAPTCHA Bot Minimum Score', 'wp-simple-firewall' ); // config_spec.options.70.name
	__( 'High Reputation Bypass', 'wp-simple-firewall' ); // config_spec.options.71.name
	__( 'Ensures that visitors with a high reputation are never blocked by Shield.', 'wp-simple-firewall' ); // config_spec.options.71.description
	__( 'Offense Limit', 'wp-simple-firewall' ); // config_spec.options.72.name
	__( 'Visitor IP address will be Black Listed after X bad actions on your site', 'wp-simple-firewall' ); // config_spec.options.72.summary
	__( 'A black mark is set against an IP address each time a visitor trips the defenses of the Shield plugin. When the number of these offenses exceeds specified limit, they are automatically blocked from accessing the site. Set this to 0 to turn off the Automatic IP Black List feature.', 'wp-simple-firewall' ); // config_spec.options.72.description
	__( 'Auto Block Expiration', 'wp-simple-firewall' ); // config_spec.options.73.name
	__( "After 1 'X' a black listed IP will be removed from the black list", 'wp-simple-firewall' ); // config_spec.options.73.summary
	__( 'Permanent and lengthy IP Black Lists are harmful to performance. You should allow IP addresses on the black list to be eventually removed over time. Shorter IP black lists are more efficient and a more intelligent use of an IP-based blocking system.', 'wp-simple-firewall' ); // config_spec.options.73.description
	__( 'User Auto Unblock', 'wp-simple-firewall' ); // config_spec.options.74.name
	__( 'Allow Visitors To Unblock Their IP', 'wp-simple-firewall' ); // config_spec.options.74.summary
	__( 'Allow visitors blocked by the plugin to automatically unblock themselves.', 'wp-simple-firewall' ); // config_spec.options.74.description
	__( 'Request Path Whitelist', 'wp-simple-firewall' ); // config_spec.options.75.summary
	__( 'Request Path Whitelist.', 'wp-simple-firewall' ); // config_spec.options.75.description
	__( 'CrowdSec IP Blocking', 'wp-simple-firewall' ); // config_spec.options.76.name
	__( 'How To Handle Requests From IPs Found On CrowdSec Blocklist', 'wp-simple-firewall' ); // config_spec.options.76.summary
	__( "How should Shield block requests from IP address that are found on CrowdSec's list of malicious IP addresses.", 'wp-simple-firewall' ); // config_spec.options.76.description
	__( 'Enroll ID', 'wp-simple-firewall' ); // config_spec.options.77.name
	__( 'CrowdSec Enroll ID', 'wp-simple-firewall' ); // config_spec.options.77.summary
	__( 'CrowdSec Enroll ID.', 'wp-simple-firewall' ); // config_spec.options.77.description
	__( 'Failed Login', 'wp-simple-firewall' ); // config_spec.options.78.name
	__( 'Detect Failed Login Attempts By Valid Usernames', 'wp-simple-firewall' ); // config_spec.options.78.summary
	__( 'Penalise a visitor who fails to login using a valid username.', 'wp-simple-firewall' ); // config_spec.options.78.description
	__( 'XML-RPC Access', 'wp-simple-firewall' ); // config_spec.options.79.name
	__( 'Identify A Bot When It Accesses XML-RPC', 'wp-simple-firewall' ); // config_spec.options.79.summary
	__( "If you don't use XML-RPC, why would anyone access it?", 'wp-simple-firewall' ); // config_spec.options.79.description
	__( 'Invalid Usernames', 'wp-simple-firewall' ); // config_spec.options.80.name
	__( 'Detect Invalid Username Logins', 'wp-simple-firewall' ); // config_spec.options.80.summary
	__( 'Identify A Bot When It Tries To Login With A Non-Existent Username.', 'wp-simple-firewall' ); // config_spec.options.80.description
	__( 'Fake Web Crawler', 'wp-simple-firewall' ); // config_spec.options.81.name
	__( 'Detect Fake Search Engine Crawlers', 'wp-simple-firewall' ); // config_spec.options.81.summary
	__( "Identify a Bot when it presents as an official web crawler, but analysis shows it's fake.", 'wp-simple-firewall' ); // config_spec.options.81.description
	__( '404 Detect', 'wp-simple-firewall' ); // config_spec.options.82.name
	__( 'Identify A Bot When It Hits A 404', 'wp-simple-firewall' ); // config_spec.options.82.summary
	__( 'Detect When A Visitor Browses To A Non-Existent Page.', 'wp-simple-firewall' ); // config_spec.options.82.description
	__( 'Link Cheese', 'wp-simple-firewall' ); // config_spec.options.83.name
	__( 'Tempt A Bot With A Fake Link To Follow', 'wp-simple-firewall' ); // config_spec.options.83.summary
	__( "Detect A Bot That Follows A 'no-follow' Link.", 'wp-simple-firewall' ); // config_spec.options.83.description
	__( 'Invalid Script Load', 'wp-simple-firewall' ); // config_spec.options.84.name
	__( 'Identify A Bot Attempts To Load WordPress In A Non-Standard Way', 'wp-simple-firewall' ); // config_spec.options.84.summary
	__( 'WordPress should only be loaded in a limited number of ways.', 'wp-simple-firewall' ); // config_spec.options.84.description
	__( 'Empty User Agents', 'wp-simple-firewall' ); // config_spec.options.85.name
	__( 'Detect Requests With Empty User Agents', 'wp-simple-firewall' ); // config_spec.options.85.summary
	__( 'Identify a request as a bot if the user agent is not provided.', 'wp-simple-firewall' ); // config_spec.options.85.description
	__( 'Disable XML-RPC', 'wp-simple-firewall' ); // config_spec.options.94.name
	__( 'Disable The XML-RPC System', 'wp-simple-firewall' ); // config_spec.options.94.summary
	__( 'Checking this option will completely turn off the whole XML-RPC system.', 'wp-simple-firewall' ); // config_spec.options.94.description
	__( 'Anonymous Rest API', 'wp-simple-firewall' ); // config_spec.options.95.name
	__( 'Disable The Anonymous Rest API', 'wp-simple-firewall' ); // config_spec.options.95.summary
	__( 'Checking this option will completely turn off the whole Anonymous Rest API system.', 'wp-simple-firewall' ); // config_spec.options.95.description
	__( 'Rest API Exclusions', 'wp-simple-firewall' ); // config_spec.options.96.name
	__( 'Anonymous REST API Exclusions', 'wp-simple-firewall' ); // config_spec.options.96.summary
	__( 'Any namespaces provided here will be excluded from the Anonymous API restriction.', 'wp-simple-firewall' ); // config_spec.options.96.description
	__( 'Disable File Editing', 'wp-simple-firewall' ); // config_spec.options.97.name
	__( 'Disable Ability To Edit Files From Within WordPress', 'wp-simple-firewall' ); // config_spec.options.97.summary
	__( "Removes the option to directly edit any files from within the WordPress admin area. Equivalent to setting 'DISALLOW_FILE_EDIT' to TRUE.", 'wp-simple-firewall' ); // config_spec.options.97.description
	__( 'Block Username Fishing', 'wp-simple-firewall' ); // config_spec.options.98.name
	__( 'Block the ability to discover WordPress usernames based on author IDs', 'wp-simple-firewall' ); // config_spec.options.98.summary
	__( "When enabled, any URL requests containing 'author=' will be killed. Warning: Enabling this option may interfere with expected operations of your site.", 'wp-simple-firewall' ); // config_spec.options.98.description
	__( 'Clean WP Files', 'wp-simple-firewall' ); // config_spec.options.99.name
	__( 'Automatically Delete Unnecessary WP Files', 'wp-simple-firewall' ); // config_spec.options.99.summary
	__( 'Automatically delete WordPress files like wp-config-sample.php.', 'wp-simple-firewall' ); // config_spec.options.99.description
	__( 'Hide WP Login & Admin', 'wp-simple-firewall' ); // config_spec.options.100.name
	__( 'Hide The WordPress Login And Admin Areas', 'wp-simple-firewall' ); // config_spec.options.100.summary
	__( "Creating a path here will disable your 'wp-login.php'. Only letters and numbers are permitted: abc123", 'wp-simple-firewall' ); // config_spec.options.100.description
	__( 'WP Login & Admin Redirect', 'wp-simple-firewall' ); // config_spec.options.101.name
	__( 'Automatic Redirect URL For Hidden Pages', 'wp-simple-firewall' ); // config_spec.options.101.summary
	__( 'Automatically redirect requests to this location for the hidden pages.', 'wp-simple-firewall' ); // config_spec.options.101.description
	__( 'MFA Verification Page', 'wp-simple-firewall' ); // config_spec.options.102.name
	__( 'Type Of MFA Verification Page', 'wp-simple-firewall' ); // config_spec.options.102.summary
	__( 'Choose the page type for MFA verification', 'wp-simple-firewall' ); // config_spec.options.102.description
	__( 'User 2FA Setup', 'wp-simple-firewall' ); // config_spec.options.103.name
	__( 'User 2FA Setup Page Locations', 'wp-simple-firewall' ); // config_spec.options.103.summary
	__( 'Pages available to users to configure 2FA.', 'wp-simple-firewall' ); // config_spec.options.103.description
	__( '2FA Remember Me', 'wp-simple-firewall' ); // config_spec.options.104.name
	__( 'Enter the number of days a user can bypass future MFA after a successful MFA-login. 0 to disable.', 'wp-simple-firewall' ); // config_spec.options.104.description
	__( 'Allow Backup Codes', 'wp-simple-firewall' ); // config_spec.options.105.name
	__( 'Allow Users To Generate A Backup Code', 'wp-simple-firewall' ); // config_spec.options.105.summary
	__( 'Allow users to generate a backup code that can be used to login if MFA factors are unavailable.', 'wp-simple-firewall' ); // config_spec.options.105.description
	__( 'Enable Google Authenticator', 'wp-simple-firewall' ); // config_spec.options.106.name
	__( 'Allow Users To Use Google Authenticator', 'wp-simple-firewall' ); // config_spec.options.106.summary
	__( 'When enabled, users will have the option to add Google Authenticator to their WordPress user profile.', 'wp-simple-firewall' ); // config_spec.options.106.description
	__( 'Allow Yubikey OTP', 'wp-simple-firewall' ); // config_spec.options.107.name
	__( 'Allow Yubikey Registration For One Time Passwords', 'wp-simple-firewall' ); // config_spec.options.107.summary
	__( 'Yubikey App ID', 'wp-simple-firewall' ); // config_spec.options.108.name
	__( 'Your Unique Yubikey App ID', 'wp-simple-firewall' ); // config_spec.options.108.summary
	__( 'Combined with your Yubikey API Key this will form the basis of your Yubikey Authentication.', 'wp-simple-firewall' ); // config_spec.options.108.description
	__( 'Yubikey API Key', 'wp-simple-firewall' ); // config_spec.options.109.name
	__( 'Your Unique Yubikey App API Key', 'wp-simple-firewall' ); // config_spec.options.109.summary
	__( 'Combined with your Yubikey App ID this will form the basis of your Yubikey Authentication.', 'wp-simple-firewall' ); // config_spec.options.109.description
	__( 'Enable Email Authentication', 'wp-simple-firewall' ); // config_spec.options.110.name
	__( 'Two-Factor Login Authentication By Email', 'wp-simple-firewall' ); // config_spec.options.110.summary
	__( 'All users will be required to verify their login by email-based two-factor authentication.', 'wp-simple-firewall' ); // config_spec.options.110.description
	__( 'Email Auto-Login', 'wp-simple-firewall' ); // config_spec.options.111.name
	__( 'Enable Email Auto-Login Links', 'wp-simple-firewall' ); // config_spec.options.111.summary
	__( "2FA Email will contain an auto-login link so the user doesn't need to enter 2FA code manually.", 'wp-simple-firewall' ); // config_spec.options.111.description
	__( 'Enforce - Email Authentication', 'wp-simple-firewall' ); // config_spec.options.112.name
	__( 'All User Roles Subject To Email Authentication', 'wp-simple-firewall' ); // config_spec.options.112.summary
	__( 'Enforces email-based authentication on all users with the selected roles. Note: This setting only applies to email authentication.', 'wp-simple-firewall' ); // config_spec.options.112.description
	__( 'Allow Any User', 'wp-simple-firewall' ); // config_spec.options.113.name
	__( 'Allow Any User To Turn-On Two-Factor Authentication By Email', 'wp-simple-firewall' ); // config_spec.options.113.summary
	__( 'Allow Any User To Turn-On Two-Factor Authentication By Email.', 'wp-simple-firewall' ); // config_spec.options.113.description
	__( 'Protected Forms', 'wp-simple-firewall' ); // config_spec.options.114.name
	__( 'Which WordPress Forms Should Be Protected From Bots', 'wp-simple-firewall' ); // config_spec.options.114.summary
	__( 'Choose on which forms silentCAPTHA Bot Protection will be deployed.', 'wp-simple-firewall' ); // config_spec.options.114.description
	__( 'Login Cooldown Interval', 'wp-simple-firewall' ); // config_spec.options.115.name
	__( 'Limit login attempts to every X seconds', 'wp-simple-firewall' ); // config_spec.options.115.summary
	__( 'Block Login Bots', 'wp-simple-firewall' ); // config_spec.options.116.name
	__( 'Block Login Attempted By Automated Bots', 'wp-simple-firewall' ); // config_spec.options.116.summary
	__( "Use Shield's silentCAPTCHA To Block Bots and Brute Force Attacks", 'wp-simple-firewall' ); // config_spec.options.116.description
	__( 'Bot Protection', 'wp-simple-firewall' ); // config_spec.options.117.name
	__( 'Protect WP Login From Automated Login Attempts By Bots', 'wp-simple-firewall' ); // config_spec.options.117.summary
	__( 'AntiBot Forms', 'wp-simple-firewall' ); // config_spec.options.118.name
	__( 'Enter The IDs Of The 3rd Party Login Forms For Use With AntiBot JS', 'wp-simple-firewall' ); // config_spec.options.118.summary
	__( 'Enable Passkeys', 'wp-simple-firewall' ); // config_spec.options.119.name
	__( 'Allow Registration Of Passkeys', 'wp-simple-firewall' ); // config_spec.options.119.summary
	__( 'Allow Registration Of Passkeys.', 'wp-simple-firewall' ); // config_spec.options.119.description
	__( 'Form SPAM Checking', 'wp-simple-firewall' ); // config_spec.options.121.name
	__( 'Select The Form Providers That Should Be Checked For SPAM', 'wp-simple-firewall' ); // config_spec.options.121.summary
	__( 'Select The Form Providers That Should Be Checked For SPAM.', 'wp-simple-firewall' ); // config_spec.options.121.description
	__( 'User Form Checking', 'wp-simple-firewall' ); // config_spec.options.122.name
	__( 'Select The User Form Providers That Should Be Checked For SPAM Registrations and Logins', 'wp-simple-firewall' ); // config_spec.options.122.description
	__( 'Uncheck this option to disable all Shield features', 'wp-simple-firewall' ); // config_spec.options.123.description
	__( 'Visitor IP Address', 'wp-simple-firewall' ); // config_spec.options.124.name
	__( 'Which Address Is Yours', 'wp-simple-firewall' ); // config_spec.options.124.summary
	__( 'There are many way to detect visitor IP addresses. Please select yours from the list.', 'wp-simple-firewall' ); // config_spec.options.124.description
	__( 'Report Email', 'wp-simple-firewall' ); // config_spec.options.125.name
	__( 'Email For All Reports and Plugin Notifications', 'wp-simple-firewall' ); // config_spec.options.125.summary
	__( 'Defaults to the blog admin email address.', 'wp-simple-firewall' ); // config_spec.options.125.description
	__( 'Show Plugin Badge', 'wp-simple-firewall' ); // config_spec.options.126.name
	__( 'Display Plugin Security Badge On Your Site', 'wp-simple-firewall' ); // config_spec.options.126.summary
	__( 'Enabling this option helps support the plugin by spreading the word about it on your website. The plugin badge also demonstrates to visitors that you take your website security seriously.', 'wp-simple-firewall' ); // config_spec.options.126.description
	__( 'In-Plugin Notices', 'wp-simple-firewall' ); // config_spec.options.127.name
	__( 'Display Plugin Specific Notices', 'wp-simple-firewall' ); // config_spec.options.127.summary
	__( 'Disable this option to hide certain plugin admin notices about available updates and post-update notices.', 'wp-simple-firewall' ); // config_spec.options.127.description
	__( 'Enable Information Gathering', 'wp-simple-firewall' ); // config_spec.options.128.name
	__( 'Permit Anonymous Telemetry Reports', 'wp-simple-firewall' ); // config_spec.options.128.summary
	__( 'Allows us to gather information on statistics and features in-use across our client installations. This information is strictly anonymous and contains no personally, or otherwise, identifiable data.', 'wp-simple-firewall' ); // config_spec.options.128.description
	__( 'Run In MU Mode', 'wp-simple-firewall' ); // config_spec.options.129.name
	__( 'Setup the plugin to run as an MU-plugin to prevent accidental deactivation.', 'wp-simple-firewall' ); // config_spec.options.129.description
	__( 'Self AutoUpdate', 'wp-simple-firewall' ); // config_spec.options.130.name
	__( 'Always Automatically Update This Plugin', 'wp-simple-firewall' ); // config_spec.options.130.summary
	__( 'Automatically update the Shield plugin.', 'wp-simple-firewall' ); // config_spec.options.130.description
	__( 'Delete Plugin Settings', 'wp-simple-firewall' ); // config_spec.options.131.name
	__( 'Delete All Plugin Settings Upon Plugin Deactivation', 'wp-simple-firewall' ); // config_spec.options.131.summary
	__( 'Careful: Removes all plugin options when you deactivate the plugin.', 'wp-simple-firewall' ); // config_spec.options.131.description
	__( 'Temp Dir', 'wp-simple-firewall' ); // config_spec.options.132.name
	__( 'Preferred Temporary Directory', 'wp-simple-firewall' ); // config_spec.options.132.summary
	__( 'Preferred temporary directory override.', 'wp-simple-firewall' ); // config_spec.options.132.description
	__( 'Beta Access', 'wp-simple-firewall' ); // config_spec.options.133.name
	__( 'Enable Access To Beta Versions', 'wp-simple-firewall' ); // config_spec.options.133.summary
	__( 'Enable This Option To Allow Shield To Upgrade To Beta and Pre-Release Versions', 'wp-simple-firewall' ); // config_spec.options.133.description
	__( 'Allow Import Of Options To, And Export Of Options From, This Site', 'wp-simple-firewall' ); // config_spec.options.134.summary
	__( 'Uncheck this box to completely disable import and export of options.', 'wp-simple-firewall' ); // config_spec.options.134.description
	__( 'Auto-Import URL', 'wp-simple-firewall' ); // config_spec.options.135.name
	__( 'Automatically Import Options From This Site', 'wp-simple-firewall' ); // config_spec.options.135.summary
	__( "Supplying a valid site URL here will make this site an 'Options Slave' and will automatically import options daily.", 'wp-simple-firewall' ); // config_spec.options.135.description
	__( 'Export Whitelist', 'wp-simple-firewall' ); // config_spec.options.136.name
	__( 'Whitelisted Sites Which Do Not Need The Secret Key To Export Options', 'wp-simple-firewall' ); // config_spec.options.136.summary
	__( 'Each site on this list will be able to export options from this site without providing the secret key. Take a new line for each URL.', 'wp-simple-firewall' ); // config_spec.options.136.description
	__( 'Notify Whitelist', 'wp-simple-firewall' ); // config_spec.options.137.name
	__( 'Notify Sites On The Whitelist To Update Options From Master', 'wp-simple-firewall' ); // config_spec.options.137.summary
	__( 'When enabled, manual options saving will notify sites on the whitelist to export options from the Master site.', 'wp-simple-firewall' ); // config_spec.options.137.description
	__( 'Secret Key', 'wp-simple-firewall' ); // config_spec.options.138.name
	__( 'Keep this Secret Key private as it will allow the import and export of options.', 'wp-simple-firewall' ); // config_spec.options.138.description
	__( 'Alert Reports Frequency', 'wp-simple-firewall' ); // config_spec.options.139.name
	__( 'How Often Should You Be Sent Reports With Important Alerts', 'wp-simple-firewall' ); // config_spec.options.139.summary
	__( 'Decide when you should be sent reports with alerts about your site security.', 'wp-simple-firewall' ); // config_spec.options.139.description
	__( 'Info Reports Frequency', 'wp-simple-firewall' ); // config_spec.options.140.name
	__( 'How Often Should You Be Sent Information Reports', 'wp-simple-firewall' ); // config_spec.options.140.summary
	__( 'Decide when you should be sent non-critical information and reports about your site security.', 'wp-simple-firewall' ); // config_spec.options.140.description
	__( 'Shield Deactivated', 'wp-simple-firewall' ); // config_spec.options.141.name
	__( 'Be alerted when the Shield plugin is deactivated', 'wp-simple-firewall' ); // config_spec.options.141.summary
	__( 'Be alerted when the Shield plugin is deactivated.', 'wp-simple-firewall' ); // config_spec.options.141.description
	__( 'Admin Accounts', 'wp-simple-firewall' ); // config_spec.options.142.name
	__( 'Be alerted to any important change on any admin account', 'wp-simple-firewall' ); // config_spec.options.142.summary
	__( 'Be alerted to any important change on any admin account.', 'wp-simple-firewall' ); // config_spec.options.142.description
	__( 'FileLocker Changes', 'wp-simple-firewall' ); // config_spec.options.144.name
	__( 'Be alerted to any changes to FileLocker items', 'wp-simple-firewall' ); // config_spec.options.144.summary
	__( 'Be alerted to any changes to FileLocker items.', 'wp-simple-firewall' ); // config_spec.options.144.description
	__( 'Block iFrames', 'wp-simple-firewall' ); // config_spec.options.145.name
	__( 'Block Remote iFrames Of This Site', 'wp-simple-firewall' ); // config_spec.options.145.summary
	__( 'The setting prevents any external website from embedding your site in an iFrame. This is useful for preventing so-called ClickJack attacks.', 'wp-simple-firewall' ); // config_spec.options.145.description
	__( 'XSS Protection', 'wp-simple-firewall' ); // config_spec.options.146.name
	__( 'Employ Built-In Browser XSS Protection', 'wp-simple-firewall' ); // config_spec.options.146.summary
	__( 'Directs compatible browsers to block what they detect as Reflective XSS attacks.', 'wp-simple-firewall' ); // config_spec.options.146.description
	__( 'Prevent Mime-Sniff', 'wp-simple-firewall' ); // config_spec.options.147.name
	__( 'Turn-Off Browser Mime-Sniff', 'wp-simple-firewall' ); // config_spec.options.147.summary
	__( 'Reduces visitor exposure to malicious user-uploaded content.', 'wp-simple-firewall' ); // config_spec.options.147.description
	__( 'Referrer Policy', 'wp-simple-firewall' ); // config_spec.options.148.name
	__( 'Referrer Policy Header', 'wp-simple-firewall' ); // config_spec.options.148.summary
	__( 'The Referrer Policy Header allows you to control when and what referral information a browser may pass along with links clicked on your site.', 'wp-simple-firewall' ); // config_spec.options.148.description
	__( 'Enable Content Security Policy', 'wp-simple-firewall' ); // config_spec.options.149.name
	__( 'Allows for permission and restriction of all resources loaded on your site.', 'wp-simple-firewall' ); // config_spec.options.149.description
	__( 'CSP Rules', 'wp-simple-firewall' ); // config_spec.options.150.name
	__( 'Provide your custom set of CSP rules.', 'wp-simple-firewall' ); // config_spec.options.150.description
	__( 'Enable Request Logging', 'wp-simple-firewall' ); // config_spec.options.170.name
	__( 'Log Requests To Your WordPress Site', 'wp-simple-firewall' ); // config_spec.options.170.summary
	__( 'Monitor web requests sent to your WordPress site.', 'wp-simple-firewall' ); // config_spec.options.170.description
	__( 'Live Logging', 'wp-simple-firewall' ); // config_spec.options.171.name
	__( 'Enable Live Logging Of All Traffic', 'wp-simple-firewall' ); // config_spec.options.171.summary
	__( 'Switch-on logging of all site traffic.', 'wp-simple-firewall' ); // config_spec.options.171.description
	__( 'Request Log Exclusions', 'wp-simple-firewall' ); // config_spec.options.172.name
	__( 'Select Which Types Of Requests To Exclude', 'wp-simple-firewall' ); // config_spec.options.172.summary
	__( "Deselect any requests that you don't want to appear in the traffic viewer.", 'wp-simple-firewall' ); // config_spec.options.172.description
	__( 'Custom Exclusions', 'wp-simple-firewall' ); // config_spec.options.173.name
	__( 'Provide Custom Traffic Exclusions', 'wp-simple-firewall' ); // config_spec.options.173.summary
	__( 'Log Retention', 'wp-simple-firewall' ); // config_spec.options.174.name
	__( 'Enable Traffic Log Auto Expiry', 'wp-simple-firewall' ); // config_spec.options.174.summary
	__( 'Enable Rate Limiting', 'wp-simple-firewall' ); // config_spec.options.175.name
	__( 'Turn On The Rate Limiting Feature', 'wp-simple-firewall' ); // config_spec.options.175.summary
	__( 'Enable or disable the rate limiting feature according to your rate limiting parameters.', 'wp-simple-firewall' ); // config_spec.options.175.description
	__( 'Max Request Limit', 'wp-simple-firewall' ); // config_spec.options.176.name
	__( 'Maximum Number Of Requests Allowed In Time Limit', 'wp-simple-firewall' ); // config_spec.options.176.summary
	__( 'The maximum number of requests that are allowed in the given time limit.', 'wp-simple-firewall' ); // config_spec.options.176.description
	__( 'Request Limit Time Interval', 'wp-simple-firewall' ); // config_spec.options.177.name
	__( 'The Time Interval To Test For Excessive Requests', 'wp-simple-firewall' ); // config_spec.options.177.summary
	__( 'The time limit within which to monitor for excessive requests that exceed the limit.', 'wp-simple-firewall' ); // config_spec.options.177.description
	__( 'User Login Notification Email', 'wp-simple-firewall' ); // config_spec.options.179.name
	__( 'Send Email Notification To Each User Upon Successful Login', 'wp-simple-firewall' ); // config_spec.options.179.summary
	__( 'A notification is sent to each user when a successful login occurs for their account.', 'wp-simple-firewall' ); // config_spec.options.179.description
	__( 'Admin Login Notification Email', 'wp-simple-firewall' ); // config_spec.options.180.name
	__( 'Send An Notification Email When Administrator Logs In', 'wp-simple-firewall' ); // config_spec.options.180.summary
	__( 'If you would like to be notified every time an administrator user logs into this WordPress site, enter a notification email address. No email address - No Notification.', 'wp-simple-firewall' ); // config_spec.options.180.description
	__( 'Session Timeout', 'wp-simple-firewall' ); // config_spec.options.181.name
	__( 'Specify How Many Days After Login To Automatically Force Re-Login', 'wp-simple-firewall' ); // config_spec.options.181.summary
	__( "WordPress default is 2 days, or 14 days if you check the 'Remember Me' box.", 'wp-simple-firewall' ); // config_spec.options.181.description
	__( 'Idle Timeout', 'wp-simple-firewall' ); // config_spec.options.182.name
	__( 'Specify How Many Hours After Inactivity To Automatically Logout User', 'wp-simple-firewall' ); // config_spec.options.182.summary
	__( "If the user is inactive for the number of hours specified, they will be forcefully logged out next time they return. Set this to '0' to turn off this option.", 'wp-simple-firewall' ); // config_spec.options.182.description
	__( 'Session Lock', 'wp-simple-firewall' ); // config_spec.options.183.name
	__( 'Lock User Sessions To ', 'wp-simple-firewall' ); // config_spec.options.183.summary
	__( 'Validate Email Addresses', 'wp-simple-firewall' ); // config_spec.options.184.name
	__( 'Validate Email Addresses When User Attempts To Register', 'wp-simple-firewall' ); // config_spec.options.184.summary
	__( 'Validate Email Addresses When User Attempts To Register.', 'wp-simple-firewall' ); // config_spec.options.184.description
	__( 'Email Checks', 'wp-simple-firewall' ); // config_spec.options.185.name
	__( 'The Email Address Properties That Will Be Tested', 'wp-simple-firewall' ); // config_spec.options.185.summary
	__( 'Enable Password Policies', 'wp-simple-firewall' ); // config_spec.options.186.name
	__( 'Enable The Password Policies Below', 'wp-simple-firewall' ); // config_spec.options.186.summary
	__( 'Prevent Pwned Passwords', 'wp-simple-firewall' ); // config_spec.options.187.name
	__( 'Prevent Use Of Pwned Passwords', 'wp-simple-firewall' ); // config_spec.options.187.summary
	__( 'Prevents users from using any passwords found on the public available list of pwned passwords.', 'wp-simple-firewall' ); // config_spec.options.187.description
	__( 'Minimum Strength', 'wp-simple-firewall' ); // config_spec.options.188.name
	__( 'Minimum Password Strength', 'wp-simple-firewall' ); // config_spec.options.188.summary
	__( 'All passwords that a user sets must meet this minimum strength.', 'wp-simple-firewall' ); // config_spec.options.188.description
	__( 'Password Expiration', 'wp-simple-firewall' ); // config_spec.options.189.name
	__( 'Passwords Expire After This Many Days', 'wp-simple-firewall' ); // config_spec.options.189.summary
	__( 'Users will be forced to reset their passwords after the number of days specified.', 'wp-simple-firewall' ); // config_spec.options.189.description
	__( 'Apply To Existing Users', 'wp-simple-firewall' ); // config_spec.options.190.name
	__( 'Apply Password Policies To Existing Users and Their Passwords', 'wp-simple-firewall' ); // config_spec.options.190.summary
	__( "Forces existing users to update their passwords if they don't meet requirements, after they next login .", 'wp-simple-firewall' ); // config_spec.options.190.description
	__( 'Allow Manual User Suspension', 'wp-simple-firewall' ); // config_spec.options.191.name
	__( 'Manually Suspend User Accounts To Prevent Login', 'wp-simple-firewall' ); // config_spec.options.191.summary
	__( 'Users may be suspended by administrators to prevent login.', 'wp-simple-firewall' ); // config_spec.options.191.description
	__( 'Auto-Suspend Expired Passwords', 'wp-simple-firewall' ); // config_spec.options.192.name
	__( 'Automatically Suspend Users With Expired Passwords', 'wp-simple-firewall' ); // config_spec.options.192.summary
	__( 'Suspend login by users and require password reset to unsuspend.', 'wp-simple-firewall' ); // config_spec.options.192.description
	__( 'Auto-Suspend Idle Users', 'wp-simple-firewall' ); // config_spec.options.194.name
	__( 'Automatically Suspend Idle User Accounts', 'wp-simple-firewall' ); // config_spec.options.194.summary
	__( 'Prevent login by idle users and require password reset to unsuspend.', 'wp-simple-firewall' ); // config_spec.options.194.description
	__( 'Activity Logs', 'wp-simple-firewall' ); // config_spec.databases.tables.activity_logs.name
	__( 'Activity Log Meta Data', 'wp-simple-firewall' ); // config_spec.databases.tables.activity_logs_meta.name
	__( 'Site Snapshots', 'wp-simple-firewall' ); // config_spec.databases.tables.activity_snapshots.name
	__( 'Bot Signals Tracking', 'wp-simple-firewall' ); // config_spec.databases.tables.bot_signals.name
	__( 'CrowdSec Signals', 'wp-simple-firewall' ); // config_spec.databases.tables.crowdsec_signals.name
	__( 'Shield Events & Stats', 'wp-simple-firewall' ); // config_spec.databases.tables.events.name
	__( 'File Locker Data', 'wp-simple-firewall' ); // config_spec.databases.tables.file_locker.name
	__( 'IP Addresses', 'wp-simple-firewall' ); // config_spec.databases.tables.ips.name
	__( 'IP Meta', 'wp-simple-firewall' ); // config_spec.databases.tables.ip_meta.name
	__( 'IP Rules', 'wp-simple-firewall' ); // config_spec.databases.tables.ip_rules.name
	__( 'Malware File Tracking', 'wp-simple-firewall' ); // config_spec.databases.tables.malware.name
	__( 'Security Reports', 'wp-simple-firewall' ); // config_spec.databases.tables.reports.name
	__( 'Request Logs', 'wp-simple-firewall' ); // config_spec.databases.tables.req_logs.name
	__( 'Scan Result Items', 'wp-simple-firewall' ); // config_spec.databases.tables.scan_result_items.name
	__( 'Scan Result Items Metadata', 'wp-simple-firewall' ); // config_spec.databases.tables.scan_result_item_meta.name
	__( 'Scan Items', 'wp-simple-firewall' ); // config_spec.databases.tables.scan_items.name
	__( 'Scan Result Sets', 'wp-simple-firewall' ); // config_spec.databases.tables.scan_results.name
	__( 'User Meta', 'wp-simple-firewall' ); // config_spec.databases.tables.user_meta.name

}
