name: Shield Security CI

on:
  push:
    branches: [ feature/claude, feature/expanded_testing, develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test:
    name: 'Test (PHP ${{ matrix.php }})'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        tools: composer:v2
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        composer install --no-interaction --prefer-dist --optimize-autoloader
        cd src/lib && composer install --no-interaction --prefer-dist --optimize-autoloader
        cd ../..
        npm ci --no-audit --no-fund
        
    - name: Build assets
      run: npm run build
      
    - name: Build plugin package
      run: |
        PACKAGE_DIR="${{ github.workspace }}/shield-package"
        ./bin/build-package.sh "$PACKAGE_DIR" "${{ github.workspace }}"
        echo "SHIELD_PACKAGE_PATH=$PACKAGE_DIR" >> $GITHUB_ENV
        
    - name: Install WordPress Test Suite
      run: |
        sudo apt-get update && sudo apt-get install -y subversion
        bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:3306 latest
        
    - name: Run tests
      run: SHIELD_PACKAGE_PATH="${{ env.SHIELD_PACKAGE_PATH }}" composer test

