name: Unit Serial Sentinel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  unit-serial-sentinel:
    name: 'Unit Serial Sentinel'
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      run_command: composer test:unit:serial
